# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.pagination import AsyncPager, SyncPager
from ...core.request_options import RequestOptions
from ...types.entity_channel_list_response import EntityChannelListResponse
from ...types.entity_channel_list_response_items_item import EntityChannelListResponseItemsItem
from ...types.entity_organization_list_response import EntityOrganizationListResponse
from ...types.entity_organization_list_response_items_item import EntityOrganizationListResponseItemsItem
from ...types.entity_people_list_response import EntityPeopleListResponse
from ...types.entity_people_list_response_items_item import EntityPeopleListResponseItemsItem
from ...types.entity_product_list_response import EntityProductListResponse
from ...types.entity_product_list_response_items_item import EntityProductListResponseItemsItem
from ...types.entity_topic_list_response import EntityTopicListResponse
from ...types.entity_topic_list_response_items_item import EntityTopicListResponseItemsItem
from .raw_client import AsyncRawRelatedClient, RawRelatedClient
from .types.channels_related_request_order import ChannelsRelatedRequestOrder
from .types.organizations_related_request_order import OrganizationsRelatedRequestOrder
from .types.people_related_request_order import PeopleRelatedRequestOrder
from .types.products_related_request_order import ProductsRelatedRequestOrder
from .types.topics_related_request_order import TopicsRelatedRequestOrder


class RelatedClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawRelatedClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawRelatedClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawRelatedClient
        """
        return self._raw_client

    def topics(
        self,
        slug: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        field: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        order: typing.Optional[TopicsRelatedRequestOrder] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[EntityTopicListResponseItemsItem, EntityTopicListResponse]:
        """
        The topics that co-occur with this channel in indexed media, with q/field/sort/order filtering. Cursor-paginated: rows are in items, and next_cursor (null on the last page) feeds the cursor parameter for the next page. total, offset, limit and hasMore mirror the web shape.

        Parameters
        ----------
        slug : str
            The entity slug: the last segment of its arcmira.com page URL, as EntityRef.slug carries it.

        limit : typing.Optional[int]

        cursor : typing.Optional[str]
            Opaque cursor from a previous page's next_cursor.

        q : typing.Optional[str]
            Substring filter over the row's text columns (e.g. video title, channel name, description).

        field : typing.Optional[str]
            Restrict the q filter to one column. Default "any" (all searchable columns).

        sort : typing.Optional[str]
            Sort key. Rows default to newest first; supported values vary by list (e.g. "date", "channel").

        order : typing.Optional[TopicsRelatedRequestOrder]
            Sort direction. Default desc.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[EntityTopicListResponseItemsItem, EntityTopicListResponse]
            Success

        Examples
        --------
        from arcmira import Arcmira

        client = Arcmira(
            api_key="YOUR_API_KEY",
        )
        response = client.channels.related.topics(
            slug="slug",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.topics(
            slug, limit=limit, cursor=cursor, q=q, field=field, sort=sort, order=order, request_options=request_options
        )

    def people(
        self,
        slug: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        field: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        order: typing.Optional[PeopleRelatedRequestOrder] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[EntityPeopleListResponseItemsItem, EntityPeopleListResponse]:
        """
        The people that co-occur with this channel in indexed media, with q/field/sort/order filtering. Cursor-paginated: rows are in items, and next_cursor (null on the last page) feeds the cursor parameter for the next page. total, offset, limit and hasMore mirror the web shape.

        Parameters
        ----------
        slug : str
            The entity slug: the last segment of its arcmira.com page URL, as EntityRef.slug carries it.

        limit : typing.Optional[int]

        cursor : typing.Optional[str]
            Opaque cursor from a previous page's next_cursor.

        q : typing.Optional[str]
            Substring filter over the row's text columns (e.g. video title, channel name, description).

        field : typing.Optional[str]
            Restrict the q filter to one column. Default "any" (all searchable columns).

        sort : typing.Optional[str]
            Sort key. Rows default to newest first; supported values vary by list (e.g. "date", "channel").

        order : typing.Optional[PeopleRelatedRequestOrder]
            Sort direction. Default desc.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[EntityPeopleListResponseItemsItem, EntityPeopleListResponse]
            Success

        Examples
        --------
        from arcmira import Arcmira

        client = Arcmira(
            api_key="YOUR_API_KEY",
        )
        response = client.channels.related.people(
            slug="slug",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.people(
            slug, limit=limit, cursor=cursor, q=q, field=field, sort=sort, order=order, request_options=request_options
        )

    def organizations(
        self,
        slug: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        field: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        order: typing.Optional[OrganizationsRelatedRequestOrder] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[EntityOrganizationListResponseItemsItem, EntityOrganizationListResponse]:
        """
        The organizations that co-occur with this channel in indexed media, with q/field/sort/order filtering. Cursor-paginated: rows are in items, and next_cursor (null on the last page) feeds the cursor parameter for the next page. total, offset, limit and hasMore mirror the web shape.

        Parameters
        ----------
        slug : str
            The entity slug: the last segment of its arcmira.com page URL, as EntityRef.slug carries it.

        limit : typing.Optional[int]

        cursor : typing.Optional[str]
            Opaque cursor from a previous page's next_cursor.

        q : typing.Optional[str]
            Substring filter over the row's text columns (e.g. video title, channel name, description).

        field : typing.Optional[str]
            Restrict the q filter to one column. Default "any" (all searchable columns).

        sort : typing.Optional[str]
            Sort key. Rows default to newest first; supported values vary by list (e.g. "date", "channel").

        order : typing.Optional[OrganizationsRelatedRequestOrder]
            Sort direction. Default desc.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[EntityOrganizationListResponseItemsItem, EntityOrganizationListResponse]
            Success

        Examples
        --------
        from arcmira import Arcmira

        client = Arcmira(
            api_key="YOUR_API_KEY",
        )
        response = client.channels.related.organizations(
            slug="slug",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.organizations(
            slug, limit=limit, cursor=cursor, q=q, field=field, sort=sort, order=order, request_options=request_options
        )

    def products(
        self,
        slug: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        field: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        order: typing.Optional[ProductsRelatedRequestOrder] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[EntityProductListResponseItemsItem, EntityProductListResponse]:
        """
        The products that co-occur with this channel in indexed media, with q/field/sort/order filtering. Cursor-paginated: rows are in items, and next_cursor (null on the last page) feeds the cursor parameter for the next page. total, offset, limit and hasMore mirror the web shape.

        Parameters
        ----------
        slug : str
            The entity slug: the last segment of its arcmira.com page URL, as EntityRef.slug carries it.

        limit : typing.Optional[int]

        cursor : typing.Optional[str]
            Opaque cursor from a previous page's next_cursor.

        q : typing.Optional[str]
            Substring filter over the row's text columns (e.g. video title, channel name, description).

        field : typing.Optional[str]
            Restrict the q filter to one column. Default "any" (all searchable columns).

        sort : typing.Optional[str]
            Sort key. Rows default to newest first; supported values vary by list (e.g. "date", "channel").

        order : typing.Optional[ProductsRelatedRequestOrder]
            Sort direction. Default desc.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[EntityProductListResponseItemsItem, EntityProductListResponse]
            Success

        Examples
        --------
        from arcmira import Arcmira

        client = Arcmira(
            api_key="YOUR_API_KEY",
        )
        response = client.channels.related.products(
            slug="slug",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.products(
            slug, limit=limit, cursor=cursor, q=q, field=field, sort=sort, order=order, request_options=request_options
        )

    def channels(
        self,
        slug: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        field: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        order: typing.Optional[ChannelsRelatedRequestOrder] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[EntityChannelListResponseItemsItem, EntityChannelListResponse]:
        """
        The channels that co-occur with this channel in indexed media, with q/field/sort/order filtering. Cursor-paginated: rows are in items, and next_cursor (null on the last page) feeds the cursor parameter for the next page. total, offset, limit and hasMore mirror the web shape.

        Parameters
        ----------
        slug : str
            The entity slug: the last segment of its arcmira.com page URL, as EntityRef.slug carries it.

        limit : typing.Optional[int]

        cursor : typing.Optional[str]
            Opaque cursor from a previous page's next_cursor.

        q : typing.Optional[str]
            Substring filter over the row's text columns (e.g. video title, channel name, description).

        field : typing.Optional[str]
            Restrict the q filter to one column. Default "any" (all searchable columns).

        sort : typing.Optional[str]
            Sort key. Rows default to newest first; supported values vary by list (e.g. "date", "channel").

        order : typing.Optional[ChannelsRelatedRequestOrder]
            Sort direction. Default desc.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[EntityChannelListResponseItemsItem, EntityChannelListResponse]
            Success

        Examples
        --------
        from arcmira import Arcmira

        client = Arcmira(
            api_key="YOUR_API_KEY",
        )
        response = client.channels.related.channels(
            slug="slug",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.channels(
            slug, limit=limit, cursor=cursor, q=q, field=field, sort=sort, order=order, request_options=request_options
        )


class AsyncRelatedClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawRelatedClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawRelatedClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawRelatedClient
        """
        return self._raw_client

    async def topics(
        self,
        slug: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        field: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        order: typing.Optional[TopicsRelatedRequestOrder] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[EntityTopicListResponseItemsItem, EntityTopicListResponse]:
        """
        The topics that co-occur with this channel in indexed media, with q/field/sort/order filtering. Cursor-paginated: rows are in items, and next_cursor (null on the last page) feeds the cursor parameter for the next page. total, offset, limit and hasMore mirror the web shape.

        Parameters
        ----------
        slug : str
            The entity slug: the last segment of its arcmira.com page URL, as EntityRef.slug carries it.

        limit : typing.Optional[int]

        cursor : typing.Optional[str]
            Opaque cursor from a previous page's next_cursor.

        q : typing.Optional[str]
            Substring filter over the row's text columns (e.g. video title, channel name, description).

        field : typing.Optional[str]
            Restrict the q filter to one column. Default "any" (all searchable columns).

        sort : typing.Optional[str]
            Sort key. Rows default to newest first; supported values vary by list (e.g. "date", "channel").

        order : typing.Optional[TopicsRelatedRequestOrder]
            Sort direction. Default desc.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[EntityTopicListResponseItemsItem, EntityTopicListResponse]
            Success

        Examples
        --------
        import asyncio

        from arcmira import AsyncArcmira

        client = AsyncArcmira(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.channels.related.topics(
                slug="slug",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.topics(
            slug, limit=limit, cursor=cursor, q=q, field=field, sort=sort, order=order, request_options=request_options
        )

    async def people(
        self,
        slug: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        field: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        order: typing.Optional[PeopleRelatedRequestOrder] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[EntityPeopleListResponseItemsItem, EntityPeopleListResponse]:
        """
        The people that co-occur with this channel in indexed media, with q/field/sort/order filtering. Cursor-paginated: rows are in items, and next_cursor (null on the last page) feeds the cursor parameter for the next page. total, offset, limit and hasMore mirror the web shape.

        Parameters
        ----------
        slug : str
            The entity slug: the last segment of its arcmira.com page URL, as EntityRef.slug carries it.

        limit : typing.Optional[int]

        cursor : typing.Optional[str]
            Opaque cursor from a previous page's next_cursor.

        q : typing.Optional[str]
            Substring filter over the row's text columns (e.g. video title, channel name, description).

        field : typing.Optional[str]
            Restrict the q filter to one column. Default "any" (all searchable columns).

        sort : typing.Optional[str]
            Sort key. Rows default to newest first; supported values vary by list (e.g. "date", "channel").

        order : typing.Optional[PeopleRelatedRequestOrder]
            Sort direction. Default desc.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[EntityPeopleListResponseItemsItem, EntityPeopleListResponse]
            Success

        Examples
        --------
        import asyncio

        from arcmira import AsyncArcmira

        client = AsyncArcmira(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.channels.related.people(
                slug="slug",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.people(
            slug, limit=limit, cursor=cursor, q=q, field=field, sort=sort, order=order, request_options=request_options
        )

    async def organizations(
        self,
        slug: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        field: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        order: typing.Optional[OrganizationsRelatedRequestOrder] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[EntityOrganizationListResponseItemsItem, EntityOrganizationListResponse]:
        """
        The organizations that co-occur with this channel in indexed media, with q/field/sort/order filtering. Cursor-paginated: rows are in items, and next_cursor (null on the last page) feeds the cursor parameter for the next page. total, offset, limit and hasMore mirror the web shape.

        Parameters
        ----------
        slug : str
            The entity slug: the last segment of its arcmira.com page URL, as EntityRef.slug carries it.

        limit : typing.Optional[int]

        cursor : typing.Optional[str]
            Opaque cursor from a previous page's next_cursor.

        q : typing.Optional[str]
            Substring filter over the row's text columns (e.g. video title, channel name, description).

        field : typing.Optional[str]
            Restrict the q filter to one column. Default "any" (all searchable columns).

        sort : typing.Optional[str]
            Sort key. Rows default to newest first; supported values vary by list (e.g. "date", "channel").

        order : typing.Optional[OrganizationsRelatedRequestOrder]
            Sort direction. Default desc.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[EntityOrganizationListResponseItemsItem, EntityOrganizationListResponse]
            Success

        Examples
        --------
        import asyncio

        from arcmira import AsyncArcmira

        client = AsyncArcmira(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.channels.related.organizations(
                slug="slug",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.organizations(
            slug, limit=limit, cursor=cursor, q=q, field=field, sort=sort, order=order, request_options=request_options
        )

    async def products(
        self,
        slug: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        field: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        order: typing.Optional[ProductsRelatedRequestOrder] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[EntityProductListResponseItemsItem, EntityProductListResponse]:
        """
        The products that co-occur with this channel in indexed media, with q/field/sort/order filtering. Cursor-paginated: rows are in items, and next_cursor (null on the last page) feeds the cursor parameter for the next page. total, offset, limit and hasMore mirror the web shape.

        Parameters
        ----------
        slug : str
            The entity slug: the last segment of its arcmira.com page URL, as EntityRef.slug carries it.

        limit : typing.Optional[int]

        cursor : typing.Optional[str]
            Opaque cursor from a previous page's next_cursor.

        q : typing.Optional[str]
            Substring filter over the row's text columns (e.g. video title, channel name, description).

        field : typing.Optional[str]
            Restrict the q filter to one column. Default "any" (all searchable columns).

        sort : typing.Optional[str]
            Sort key. Rows default to newest first; supported values vary by list (e.g. "date", "channel").

        order : typing.Optional[ProductsRelatedRequestOrder]
            Sort direction. Default desc.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[EntityProductListResponseItemsItem, EntityProductListResponse]
            Success

        Examples
        --------
        import asyncio

        from arcmira import AsyncArcmira

        client = AsyncArcmira(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.channels.related.products(
                slug="slug",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.products(
            slug, limit=limit, cursor=cursor, q=q, field=field, sort=sort, order=order, request_options=request_options
        )

    async def channels(
        self,
        slug: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        field: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        order: typing.Optional[ChannelsRelatedRequestOrder] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[EntityChannelListResponseItemsItem, EntityChannelListResponse]:
        """
        The channels that co-occur with this channel in indexed media, with q/field/sort/order filtering. Cursor-paginated: rows are in items, and next_cursor (null on the last page) feeds the cursor parameter for the next page. total, offset, limit and hasMore mirror the web shape.

        Parameters
        ----------
        slug : str
            The entity slug: the last segment of its arcmira.com page URL, as EntityRef.slug carries it.

        limit : typing.Optional[int]

        cursor : typing.Optional[str]
            Opaque cursor from a previous page's next_cursor.

        q : typing.Optional[str]
            Substring filter over the row's text columns (e.g. video title, channel name, description).

        field : typing.Optional[str]
            Restrict the q filter to one column. Default "any" (all searchable columns).

        sort : typing.Optional[str]
            Sort key. Rows default to newest first; supported values vary by list (e.g. "date", "channel").

        order : typing.Optional[ChannelsRelatedRequestOrder]
            Sort direction. Default desc.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[EntityChannelListResponseItemsItem, EntityChannelListResponse]
            Success

        Examples
        --------
        import asyncio

        from arcmira import AsyncArcmira

        client = AsyncArcmira(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.channels.related.channels(
                slug="slug",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.channels(
            slug, limit=limit, cursor=cursor, q=q, field=field, sort=sort, order=order, request_options=request_options
        )
