# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.monitor_delete_response import MonitorDeleteResponse
from ..types.monitor_list_response import MonitorListResponse
from ..types.monitor_mutation_response import MonitorMutationResponse
from ..types.webhook_secret_rotate_response import WebhookSecretRotateResponse
from .raw_client import AsyncRawMonitorsClient, RawMonitorsClient
from .types.create_monitors_request_notify_frequency import CreateMonitorsRequestNotifyFrequency
from .types.update_monitors_request_notify_frequency import UpdateMonitorsRequestNotifyFrequency

if typing.TYPE_CHECKING:
    from .alerts.client import AlertsClient, AsyncAlertsClient
    from .trackers.client import AsyncTrackersClient, TrackersClient
# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class MonitorsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMonitorsClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._trackers: typing.Optional[TrackersClient] = None
        self._alerts: typing.Optional[AlertsClient] = None

    @property
    def with_raw_response(self) -> RawMonitorsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMonitorsClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> MonitorListResponse:
        """
        All monitors for the account with tracker counts, alert counts for the current calendar month, and Slack display metadata. Single page, no pagination.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MonitorListResponse
            Success

        Examples
        --------
        from arcmira import Arcmira

        client = Arcmira(
            api_key="YOUR_API_KEY",
        )
        client.monitors.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def create(
        self,
        *,
        name: str,
        idempotency_key: typing.Optional[str] = None,
        notify_emails: typing.Optional[typing.Sequence[str]] = OMIT,
        notify_frequency: typing.Optional[CreateMonitorsRequestNotifyFrequency] = OMIT,
        digest_day: typing.Optional[str] = OMIT,
        digest_time: typing.Optional[str] = OMIT,
        notify_webhook: typing.Optional[bool] = OMIT,
        webhook_url: typing.Optional[str] = OMIT,
        notify_slack: typing.Optional[bool] = OMIT,
        slack_integration_id: typing.Optional[str] = OMIT,
        slack_channel_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MonitorMutationResponse:
        """
        Creating with notifyWebhook: true and a webhookUrl enables HMAC-signed webhook delivery and returns the signing secret (monitor.webhookSecret) in this response. Store it securely. A retry with the original Idempotency-Key recovers the same secret for up to 24 hours while it remains the current secret or the valid previous secret. An expired or displaced secret returns 409 idempotency_result_expired without rotating again. Reads do not expose the secret. All subsequent reads expose only webhookSecretSet and webhookSecretHint.

        Parameters
        ----------
        name : str
            Display name (1-100 characters). Required on create.

        idempotency_key : typing.Optional[str]
            Use 8 to 128 letters, numbers, underscores or hyphens per intent. Keys are scoped to the account, credential and resource family. The same key and normalized method, path and body returns the committed response with Idempotency-Replayed: true. A changed intent within the same family returns 409 idempotency_conflict. Monitor and tracker families have independent namespaces. Secret recovery is limited as described by the operation.

        notify_emails : typing.Optional[typing.Sequence[str]]
            Desired email recipients. External recipients must confirm before delivery. Free includes one additional recipient per monitor; paid plans allow up to 20 total. Default [].

        notify_frequency : typing.Optional[CreateMonitorsRequestNotifyFrequency]
            Delivery cadence. Default realtime. Values: realtime (as analysis completes), hourly (hourly digest), daily (daily digest). Free-tier email delivery is coerced to daily regardless of the value sent.

        digest_day : typing.Optional[str]
            Digest day of week. Default "monday". Consulted only by weekly digests, which are dashboard-configured today; inert for API-set frequencies.

        digest_time : typing.Optional[str]
            Digest send hour as HH:MM (account timezone). Default "09:00". Applies to daily digests.

        notify_webhook : typing.Optional[bool]
            Enable HMAC-signed webhook delivery (paid plans). When enabled together with webhookUrl, the response returns the signing secret (monitor.webhookSecret), recoverable with the original Idempotency-Key during the valid recovery window. PATCHing true also re-enables an auto-disabled webhook and resets its failure counter.

        webhook_url : typing.Optional[str]
            Destination URL for webhook alert deliveries.

        notify_slack : typing.Optional[bool]
            Enable Slack delivery. Requires a Slack integration connected in the dashboard.

        slack_integration_id : typing.Optional[str]
            Slack integration id from the dashboard OAuth flow.

        slack_channel_id : typing.Optional[str]
            Slack channel id to deliver to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MonitorMutationResponse
            Success

        Examples
        --------
        from arcmira import Arcmira

        client = Arcmira(
            api_key="YOUR_API_KEY",
        )
        client.monitors.create(
            name="name",
        )
        """
        _response = self._raw_client.create(
            name=name,
            idempotency_key=idempotency_key,
            notify_emails=notify_emails,
            notify_frequency=notify_frequency,
            digest_day=digest_day,
            digest_time=digest_time,
            notify_webhook=notify_webhook,
            webhook_url=webhook_url,
            notify_slack=notify_slack,
            slack_integration_id=slack_integration_id,
            slack_channel_id=slack_channel_id,
            request_options=request_options,
        )
        return _response.data

    def delete(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MonitorDeleteResponse:
        """
        Deletes the monitor AND every tracker inside it (trackersDeleted reports how many). Cannot be undone. Retrying with the original Idempotency-Key returns the original deleted count without deleting again.

        Parameters
        ----------
        id : str
            Monitor id.

        idempotency_key : typing.Optional[str]
            Use 8 to 128 letters, numbers, underscores or hyphens per intent. Keys are scoped to the account, credential and resource family. The same key and normalized method, path and body returns the committed response with Idempotency-Replayed: true. A changed intent within the same family returns 409 idempotency_conflict. Monitor and tracker families have independent namespaces. Secret recovery is limited as described by the operation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MonitorDeleteResponse
            Success

        Examples
        --------
        from arcmira import Arcmira

        client = Arcmira(
            api_key="YOUR_API_KEY",
        )
        client.monitors.delete(
            id="id",
        )
        """
        _response = self._raw_client.delete(id, idempotency_key=idempotency_key, request_options=request_options)
        return _response.data

    def update(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        name: typing.Optional[str] = OMIT,
        notify_emails: typing.Optional[typing.Sequence[str]] = OMIT,
        notify_frequency: typing.Optional[UpdateMonitorsRequestNotifyFrequency] = OMIT,
        digest_day: typing.Optional[str] = OMIT,
        digest_time: typing.Optional[str] = OMIT,
        notify_webhook: typing.Optional[bool] = OMIT,
        webhook_url: typing.Optional[str] = OMIT,
        notify_slack: typing.Optional[bool] = OMIT,
        slack_integration_id: typing.Optional[str] = OMIT,
        slack_channel_id: typing.Optional[str] = OMIT,
        is_paused: typing.Optional[bool] = OMIT,
        is_collapsed: typing.Optional[bool] = OMIT,
        sort_order: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MonitorMutationResponse:
        """
        A PATCH that newly enables webhook signing (turns notifyWebhook on, or sets a webhookUrl where no secret existed before) returns the signing secret (monitor.webhookSecret) in this response. Store it securely. A retry with the original Idempotency-Key recovers the same secret for up to 24 hours while it remains the current secret or the valid previous secret. An expired or displaced secret returns 409 idempotency_result_expired without rotating again. Reads do not expose the secret. Unrelated PATCHes expose only webhookSecretSet and webhookSecretHint. PATCHing notifyWebhook: true also re-enables a webhook that was auto-disabled after repeated failures and resets its failure counter.

        Parameters
        ----------
        id : str
            Monitor id.

        idempotency_key : typing.Optional[str]
            Use 8 to 128 letters, numbers, underscores or hyphens per intent. Keys are scoped to the account, credential and resource family. The same key and normalized method, path and body returns the committed response with Idempotency-Replayed: true. A changed intent within the same family returns 409 idempotency_conflict. Monitor and tracker families have independent namespaces. Secret recovery is limited as described by the operation.

        name : typing.Optional[str]
            Display name (1-100 characters). Required on create.

        notify_emails : typing.Optional[typing.Sequence[str]]
            Desired email recipients. External recipients must confirm before delivery. Free includes one additional recipient per monitor; paid plans allow up to 20 total. Default [].

        notify_frequency : typing.Optional[UpdateMonitorsRequestNotifyFrequency]
            Delivery cadence. Default realtime. Values: realtime (as analysis completes), hourly (hourly digest), daily (daily digest). Free-tier email delivery is coerced to daily regardless of the value sent.

        digest_day : typing.Optional[str]
            Digest day of week. Default "monday". Consulted only by weekly digests, which are dashboard-configured today; inert for API-set frequencies.

        digest_time : typing.Optional[str]
            Digest send hour as HH:MM (account timezone). Default "09:00". Applies to daily digests.

        notify_webhook : typing.Optional[bool]
            Enable HMAC-signed webhook delivery (paid plans). When enabled together with webhookUrl, the response returns the signing secret (monitor.webhookSecret), recoverable with the original Idempotency-Key during the valid recovery window. PATCHing true also re-enables an auto-disabled webhook and resets its failure counter.

        webhook_url : typing.Optional[str]
            Destination URL for webhook alert deliveries.

        notify_slack : typing.Optional[bool]
            Enable Slack delivery. Requires a Slack integration connected in the dashboard.

        slack_integration_id : typing.Optional[str]
            Slack integration id from the dashboard OAuth flow.

        slack_channel_id : typing.Optional[str]
            Slack channel id to deliver to.

        is_paused : typing.Optional[bool]
            Paused monitors accept config changes but do not deliver; alerts that would have fired are not queued.

        is_collapsed : typing.Optional[bool]
            Dashboard display state.

        sort_order : typing.Optional[int]
            Dashboard sort position.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MonitorMutationResponse
            Success

        Examples
        --------
        from arcmira import Arcmira

        client = Arcmira(
            api_key="YOUR_API_KEY",
        )
        client.monitors.update(
            id="id",
        )
        """
        _response = self._raw_client.update(
            id,
            idempotency_key=idempotency_key,
            name=name,
            notify_emails=notify_emails,
            notify_frequency=notify_frequency,
            digest_day=digest_day,
            digest_time=digest_time,
            notify_webhook=notify_webhook,
            webhook_url=webhook_url,
            notify_slack=notify_slack,
            slack_integration_id=slack_integration_id,
            slack_channel_id=slack_channel_id,
            is_paused=is_paused,
            is_collapsed=is_collapsed,
            sort_order=sort_order,
            request_options=request_options,
        )
        return _response.data

    def rotate_webhook_secret(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebhookSecretRotateResponse:
        """
        Generates a new signing secret and returns it in this response. Store it securely. A retry with the original Idempotency-Key recovers the same secret for up to 24 hours while it remains the current secret or the valid previous secret. An expired or displaced secret returns 409 idempotency_result_expired without rotating again. Reads do not expose the secret. Zero-downtime overlap: the previous secret remains valid until previousSecretExpiresAt (24 hours); during the window every delivery carries an additional X-Arcmira-Signature-Previous header computed with the old secret over the same {timestamp}.{payload} string, so you can verify with either secret while you roll. After the window the old secret is dropped and the extra header disappears. Rotating again during the window replaces the previous secret and resets the window. Requires a configured webhook (webhookUrl set); otherwise 409 with code webhook_not_configured. Auto-disable interplay: rotation resets webhook_failures but never re-enables a webhook that was auto-disabled after repeated failures; to resume delivery, also PATCH the monitor with notifyWebhook: true. Requires the monitors:write scope.

        Parameters
        ----------
        id : str
            Monitor id.

        idempotency_key : typing.Optional[str]
            Use 8 to 128 letters, numbers, underscores or hyphens per intent. Keys are scoped to the account, credential and resource family. The same key and normalized method, path and body returns the committed response with Idempotency-Replayed: true. A changed intent within the same family returns 409 idempotency_conflict. Monitor and tracker families have independent namespaces. Secret recovery is limited as described by the operation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookSecretRotateResponse
            Success

        Examples
        --------
        from arcmira import Arcmira

        client = Arcmira(
            api_key="YOUR_API_KEY",
        )
        client.monitors.rotate_webhook_secret(
            id="id",
        )
        """
        _response = self._raw_client.rotate_webhook_secret(
            id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    @property
    def trackers(self):
        if self._trackers is None:
            from .trackers.client import TrackersClient  # noqa: E402

            self._trackers = TrackersClient(client_wrapper=self._client_wrapper)
        return self._trackers

    @property
    def alerts(self):
        if self._alerts is None:
            from .alerts.client import AlertsClient  # noqa: E402

            self._alerts = AlertsClient(client_wrapper=self._client_wrapper)
        return self._alerts


class AsyncMonitorsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMonitorsClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._trackers: typing.Optional[AsyncTrackersClient] = None
        self._alerts: typing.Optional[AsyncAlertsClient] = None

    @property
    def with_raw_response(self) -> AsyncRawMonitorsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMonitorsClient
        """
        return self._raw_client

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> MonitorListResponse:
        """
        All monitors for the account with tracker counts, alert counts for the current calendar month, and Slack display metadata. Single page, no pagination.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MonitorListResponse
            Success

        Examples
        --------
        import asyncio

        from arcmira import AsyncArcmira

        client = AsyncArcmira(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.monitors.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def create(
        self,
        *,
        name: str,
        idempotency_key: typing.Optional[str] = None,
        notify_emails: typing.Optional[typing.Sequence[str]] = OMIT,
        notify_frequency: typing.Optional[CreateMonitorsRequestNotifyFrequency] = OMIT,
        digest_day: typing.Optional[str] = OMIT,
        digest_time: typing.Optional[str] = OMIT,
        notify_webhook: typing.Optional[bool] = OMIT,
        webhook_url: typing.Optional[str] = OMIT,
        notify_slack: typing.Optional[bool] = OMIT,
        slack_integration_id: typing.Optional[str] = OMIT,
        slack_channel_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MonitorMutationResponse:
        """
        Creating with notifyWebhook: true and a webhookUrl enables HMAC-signed webhook delivery and returns the signing secret (monitor.webhookSecret) in this response. Store it securely. A retry with the original Idempotency-Key recovers the same secret for up to 24 hours while it remains the current secret or the valid previous secret. An expired or displaced secret returns 409 idempotency_result_expired without rotating again. Reads do not expose the secret. All subsequent reads expose only webhookSecretSet and webhookSecretHint.

        Parameters
        ----------
        name : str
            Display name (1-100 characters). Required on create.

        idempotency_key : typing.Optional[str]
            Use 8 to 128 letters, numbers, underscores or hyphens per intent. Keys are scoped to the account, credential and resource family. The same key and normalized method, path and body returns the committed response with Idempotency-Replayed: true. A changed intent within the same family returns 409 idempotency_conflict. Monitor and tracker families have independent namespaces. Secret recovery is limited as described by the operation.

        notify_emails : typing.Optional[typing.Sequence[str]]
            Desired email recipients. External recipients must confirm before delivery. Free includes one additional recipient per monitor; paid plans allow up to 20 total. Default [].

        notify_frequency : typing.Optional[CreateMonitorsRequestNotifyFrequency]
            Delivery cadence. Default realtime. Values: realtime (as analysis completes), hourly (hourly digest), daily (daily digest). Free-tier email delivery is coerced to daily regardless of the value sent.

        digest_day : typing.Optional[str]
            Digest day of week. Default "monday". Consulted only by weekly digests, which are dashboard-configured today; inert for API-set frequencies.

        digest_time : typing.Optional[str]
            Digest send hour as HH:MM (account timezone). Default "09:00". Applies to daily digests.

        notify_webhook : typing.Optional[bool]
            Enable HMAC-signed webhook delivery (paid plans). When enabled together with webhookUrl, the response returns the signing secret (monitor.webhookSecret), recoverable with the original Idempotency-Key during the valid recovery window. PATCHing true also re-enables an auto-disabled webhook and resets its failure counter.

        webhook_url : typing.Optional[str]
            Destination URL for webhook alert deliveries.

        notify_slack : typing.Optional[bool]
            Enable Slack delivery. Requires a Slack integration connected in the dashboard.

        slack_integration_id : typing.Optional[str]
            Slack integration id from the dashboard OAuth flow.

        slack_channel_id : typing.Optional[str]
            Slack channel id to deliver to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MonitorMutationResponse
            Success

        Examples
        --------
        import asyncio

        from arcmira import AsyncArcmira

        client = AsyncArcmira(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.monitors.create(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            name=name,
            idempotency_key=idempotency_key,
            notify_emails=notify_emails,
            notify_frequency=notify_frequency,
            digest_day=digest_day,
            digest_time=digest_time,
            notify_webhook=notify_webhook,
            webhook_url=webhook_url,
            notify_slack=notify_slack,
            slack_integration_id=slack_integration_id,
            slack_channel_id=slack_channel_id,
            request_options=request_options,
        )
        return _response.data

    async def delete(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MonitorDeleteResponse:
        """
        Deletes the monitor AND every tracker inside it (trackersDeleted reports how many). Cannot be undone. Retrying with the original Idempotency-Key returns the original deleted count without deleting again.

        Parameters
        ----------
        id : str
            Monitor id.

        idempotency_key : typing.Optional[str]
            Use 8 to 128 letters, numbers, underscores or hyphens per intent. Keys are scoped to the account, credential and resource family. The same key and normalized method, path and body returns the committed response with Idempotency-Replayed: true. A changed intent within the same family returns 409 idempotency_conflict. Monitor and tracker families have independent namespaces. Secret recovery is limited as described by the operation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MonitorDeleteResponse
            Success

        Examples
        --------
        import asyncio

        from arcmira import AsyncArcmira

        client = AsyncArcmira(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.monitors.delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id, idempotency_key=idempotency_key, request_options=request_options)
        return _response.data

    async def update(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        name: typing.Optional[str] = OMIT,
        notify_emails: typing.Optional[typing.Sequence[str]] = OMIT,
        notify_frequency: typing.Optional[UpdateMonitorsRequestNotifyFrequency] = OMIT,
        digest_day: typing.Optional[str] = OMIT,
        digest_time: typing.Optional[str] = OMIT,
        notify_webhook: typing.Optional[bool] = OMIT,
        webhook_url: typing.Optional[str] = OMIT,
        notify_slack: typing.Optional[bool] = OMIT,
        slack_integration_id: typing.Optional[str] = OMIT,
        slack_channel_id: typing.Optional[str] = OMIT,
        is_paused: typing.Optional[bool] = OMIT,
        is_collapsed: typing.Optional[bool] = OMIT,
        sort_order: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MonitorMutationResponse:
        """
        A PATCH that newly enables webhook signing (turns notifyWebhook on, or sets a webhookUrl where no secret existed before) returns the signing secret (monitor.webhookSecret) in this response. Store it securely. A retry with the original Idempotency-Key recovers the same secret for up to 24 hours while it remains the current secret or the valid previous secret. An expired or displaced secret returns 409 idempotency_result_expired without rotating again. Reads do not expose the secret. Unrelated PATCHes expose only webhookSecretSet and webhookSecretHint. PATCHing notifyWebhook: true also re-enables a webhook that was auto-disabled after repeated failures and resets its failure counter.

        Parameters
        ----------
        id : str
            Monitor id.

        idempotency_key : typing.Optional[str]
            Use 8 to 128 letters, numbers, underscores or hyphens per intent. Keys are scoped to the account, credential and resource family. The same key and normalized method, path and body returns the committed response with Idempotency-Replayed: true. A changed intent within the same family returns 409 idempotency_conflict. Monitor and tracker families have independent namespaces. Secret recovery is limited as described by the operation.

        name : typing.Optional[str]
            Display name (1-100 characters). Required on create.

        notify_emails : typing.Optional[typing.Sequence[str]]
            Desired email recipients. External recipients must confirm before delivery. Free includes one additional recipient per monitor; paid plans allow up to 20 total. Default [].

        notify_frequency : typing.Optional[UpdateMonitorsRequestNotifyFrequency]
            Delivery cadence. Default realtime. Values: realtime (as analysis completes), hourly (hourly digest), daily (daily digest). Free-tier email delivery is coerced to daily regardless of the value sent.

        digest_day : typing.Optional[str]
            Digest day of week. Default "monday". Consulted only by weekly digests, which are dashboard-configured today; inert for API-set frequencies.

        digest_time : typing.Optional[str]
            Digest send hour as HH:MM (account timezone). Default "09:00". Applies to daily digests.

        notify_webhook : typing.Optional[bool]
            Enable HMAC-signed webhook delivery (paid plans). When enabled together with webhookUrl, the response returns the signing secret (monitor.webhookSecret), recoverable with the original Idempotency-Key during the valid recovery window. PATCHing true also re-enables an auto-disabled webhook and resets its failure counter.

        webhook_url : typing.Optional[str]
            Destination URL for webhook alert deliveries.

        notify_slack : typing.Optional[bool]
            Enable Slack delivery. Requires a Slack integration connected in the dashboard.

        slack_integration_id : typing.Optional[str]
            Slack integration id from the dashboard OAuth flow.

        slack_channel_id : typing.Optional[str]
            Slack channel id to deliver to.

        is_paused : typing.Optional[bool]
            Paused monitors accept config changes but do not deliver; alerts that would have fired are not queued.

        is_collapsed : typing.Optional[bool]
            Dashboard display state.

        sort_order : typing.Optional[int]
            Dashboard sort position.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MonitorMutationResponse
            Success

        Examples
        --------
        import asyncio

        from arcmira import AsyncArcmira

        client = AsyncArcmira(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.monitors.update(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            id,
            idempotency_key=idempotency_key,
            name=name,
            notify_emails=notify_emails,
            notify_frequency=notify_frequency,
            digest_day=digest_day,
            digest_time=digest_time,
            notify_webhook=notify_webhook,
            webhook_url=webhook_url,
            notify_slack=notify_slack,
            slack_integration_id=slack_integration_id,
            slack_channel_id=slack_channel_id,
            is_paused=is_paused,
            is_collapsed=is_collapsed,
            sort_order=sort_order,
            request_options=request_options,
        )
        return _response.data

    async def rotate_webhook_secret(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebhookSecretRotateResponse:
        """
        Generates a new signing secret and returns it in this response. Store it securely. A retry with the original Idempotency-Key recovers the same secret for up to 24 hours while it remains the current secret or the valid previous secret. An expired or displaced secret returns 409 idempotency_result_expired without rotating again. Reads do not expose the secret. Zero-downtime overlap: the previous secret remains valid until previousSecretExpiresAt (24 hours); during the window every delivery carries an additional X-Arcmira-Signature-Previous header computed with the old secret over the same {timestamp}.{payload} string, so you can verify with either secret while you roll. After the window the old secret is dropped and the extra header disappears. Rotating again during the window replaces the previous secret and resets the window. Requires a configured webhook (webhookUrl set); otherwise 409 with code webhook_not_configured. Auto-disable interplay: rotation resets webhook_failures but never re-enables a webhook that was auto-disabled after repeated failures; to resume delivery, also PATCH the monitor with notifyWebhook: true. Requires the monitors:write scope.

        Parameters
        ----------
        id : str
            Monitor id.

        idempotency_key : typing.Optional[str]
            Use 8 to 128 letters, numbers, underscores or hyphens per intent. Keys are scoped to the account, credential and resource family. The same key and normalized method, path and body returns the committed response with Idempotency-Replayed: true. A changed intent within the same family returns 409 idempotency_conflict. Monitor and tracker families have independent namespaces. Secret recovery is limited as described by the operation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookSecretRotateResponse
            Success

        Examples
        --------
        import asyncio

        from arcmira import AsyncArcmira

        client = AsyncArcmira(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.monitors.rotate_webhook_secret(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.rotate_webhook_secret(
            id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    @property
    def trackers(self):
        if self._trackers is None:
            from .trackers.client import AsyncTrackersClient  # noqa: E402

            self._trackers = AsyncTrackersClient(client_wrapper=self._client_wrapper)
        return self._trackers

    @property
    def alerts(self):
        if self._alerts is None:
            from .alerts.client import AsyncAlertsClient  # noqa: E402

            self._alerts = AsyncAlertsClient(client_wrapper=self._client_wrapper)
        return self._alerts
