# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.person_page_response import PersonPageResponse
from .raw_client import AsyncRawPeopleClient, RawPeopleClient

if typing.TYPE_CHECKING:
    from .appearances.client import AppearancesClient, AsyncAppearancesClient
    from .related.client import AsyncRelatedClient, RelatedClient


class PeopleClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPeopleClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._appearances: typing.Optional[AppearancesClient] = None
        self._related: typing.Optional[RelatedClient] = None

    @property
    def with_raw_response(self) -> RawPeopleClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPeopleClient
        """
        return self._raw_client

    def get(self, slug: str, *, request_options: typing.Optional[RequestOptions] = None) -> PersonPageResponse:
        """
        Parameters
        ----------
        slug : str
            The entity slug: the last segment of its arcmira.com page URL, as EntityRef.slug carries it.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PersonPageResponse
            Success

        Examples
        --------
        from arcmira import Arcmira

        client = Arcmira(
            api_key="YOUR_API_KEY",
        )
        client.people.get(
            slug="slug",
        )
        """
        _response = self._raw_client.get(slug, request_options=request_options)
        return _response.data

    @property
    def appearances(self):
        if self._appearances is None:
            from .appearances.client import AppearancesClient  # noqa: E402

            self._appearances = AppearancesClient(client_wrapper=self._client_wrapper)
        return self._appearances

    @property
    def related(self):
        if self._related is None:
            from .related.client import RelatedClient  # noqa: E402

            self._related = RelatedClient(client_wrapper=self._client_wrapper)
        return self._related


class AsyncPeopleClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPeopleClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._appearances: typing.Optional[AsyncAppearancesClient] = None
        self._related: typing.Optional[AsyncRelatedClient] = None

    @property
    def with_raw_response(self) -> AsyncRawPeopleClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPeopleClient
        """
        return self._raw_client

    async def get(self, slug: str, *, request_options: typing.Optional[RequestOptions] = None) -> PersonPageResponse:
        """
        Parameters
        ----------
        slug : str
            The entity slug: the last segment of its arcmira.com page URL, as EntityRef.slug carries it.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PersonPageResponse
            Success

        Examples
        --------
        import asyncio

        from arcmira import AsyncArcmira

        client = AsyncArcmira(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.people.get(
                slug="slug",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(slug, request_options=request_options)
        return _response.data

    @property
    def appearances(self):
        if self._appearances is None:
            from .appearances.client import AsyncAppearancesClient  # noqa: E402

            self._appearances = AsyncAppearancesClient(client_wrapper=self._client_wrapper)
        return self._appearances

    @property
    def related(self):
        if self._related is None:
            from .related.client import AsyncRelatedClient  # noqa: E402

            self._related = AsyncRelatedClient(client_wrapper=self._client_wrapper)
        return self._related
