# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class SubmitCorrectionsRequestAnchor(UniversalBaseModel):
    """
    Required for line_edit, speaker_reassign, entity_tag, and segment_rewrite.
    """

    segment_index: typing_extensions.Annotated[
        int, FieldMetadata(alias="segmentIndex"), pydantic.Field(alias="segmentIndex")
    ]
    content_hash: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="contentHash"),
        pydantic.Field(
            alias="contentHash",
            description="djb2 hash of the covered segment text (joined with \\n for ranges), computed against your projected view of the transcript.",
        ),
    ]
    """
    djb2 hash of the covered segment text (joined with \\n for ranges), computed against your projected view of the transcript.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
