# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.monitor_add_trackers_response import MonitorAddTrackersResponse
from ...types.monitor_trackers_response import MonitorTrackersResponse
from .raw_client import AsyncRawTrackersClient, RawTrackersClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TrackersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTrackersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTrackersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTrackersClient
        """
        return self._raw_client

    def list(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> MonitorTrackersResponse:
        """
        Parameters
        ----------
        id : str
            Monitor id.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MonitorTrackersResponse
            Success

        Examples
        --------
        from arcmira import Arcmira

        client = Arcmira(
            api_key="YOUR_API_KEY",
        )
        client.monitors.trackers.list(
            id="id",
        )
        """
        _response = self._raw_client.list(id, request_options=request_options)
        return _response.data

    def add(
        self,
        id: str,
        *,
        tracker_ids: typing.Sequence[str],
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MonitorAddTrackersResponse:
        """
        Attaches EXISTING trackers to the monitor by id ({ trackerIds: ["trk_..."] }). It does not create trackers: create them first via POST /v1/trackers, then attach. Attached trackers use the monitor's delivery settings. Supply 1 to 90 IDs. Duplicate IDs count once. Every ID must belong to the account; a missing or foreign ID returns tracker_not_found and none are attached. attachedCount reports the unique attached count.

        Parameters
        ----------
        id : str
            Monitor id.

        tracker_ids : typing.Sequence[str]
            Ids of existing trackers ("trk_...") to attach to this monitor. Create trackers first via POST /v1/trackers. At most 90 IDs per request; duplicates count once. All IDs must belong to the account or none are attached.

        idempotency_key : typing.Optional[str]
            One key per intent, 1 to 255 printable ASCII characters (0x21 to 0x7E); anything else is 400 invalid_idempotency_key. Keys are scoped to the account, credential and resource family. The same key and normalized method, path and body returns the committed response with Idempotency-Replayed: true. A changed intent within the same family returns 409 idempotency_conflict. Monitor and tracker families have independent namespaces. Secret recovery is limited as described by the operation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MonitorAddTrackersResponse
            Success

        Examples
        --------
        from arcmira import Arcmira

        client = Arcmira(
            api_key="YOUR_API_KEY",
        )
        client.monitors.trackers.add(
            id="id",
            idempotency_key="8b2f6c3e-4d1a-4e7b-9c05-2f6a1b7d3e90",
            tracker_ids=["trackerIds"],
        )
        """
        _response = self._raw_client.add(
            id, tracker_ids=tracker_ids, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data


class AsyncTrackersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTrackersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTrackersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTrackersClient
        """
        return self._raw_client

    async def list(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MonitorTrackersResponse:
        """
        Parameters
        ----------
        id : str
            Monitor id.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MonitorTrackersResponse
            Success

        Examples
        --------
        import asyncio

        from arcmira import AsyncArcmira

        client = AsyncArcmira(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.monitors.trackers.list(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(id, request_options=request_options)
        return _response.data

    async def add(
        self,
        id: str,
        *,
        tracker_ids: typing.Sequence[str],
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MonitorAddTrackersResponse:
        """
        Attaches EXISTING trackers to the monitor by id ({ trackerIds: ["trk_..."] }). It does not create trackers: create them first via POST /v1/trackers, then attach. Attached trackers use the monitor's delivery settings. Supply 1 to 90 IDs. Duplicate IDs count once. Every ID must belong to the account; a missing or foreign ID returns tracker_not_found and none are attached. attachedCount reports the unique attached count.

        Parameters
        ----------
        id : str
            Monitor id.

        tracker_ids : typing.Sequence[str]
            Ids of existing trackers ("trk_...") to attach to this monitor. Create trackers first via POST /v1/trackers. At most 90 IDs per request; duplicates count once. All IDs must belong to the account or none are attached.

        idempotency_key : typing.Optional[str]
            One key per intent, 1 to 255 printable ASCII characters (0x21 to 0x7E); anything else is 400 invalid_idempotency_key. Keys are scoped to the account, credential and resource family. The same key and normalized method, path and body returns the committed response with Idempotency-Replayed: true. A changed intent within the same family returns 409 idempotency_conflict. Monitor and tracker families have independent namespaces. Secret recovery is limited as described by the operation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MonitorAddTrackersResponse
            Success

        Examples
        --------
        import asyncio

        from arcmira import AsyncArcmira

        client = AsyncArcmira(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.monitors.trackers.add(
                id="id",
                idempotency_key="8b2f6c3e-4d1a-4e7b-9c05-2f6a1b7d3e90",
                tracker_ids=["trackerIds"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add(
            id, tracker_ids=tracker_ids, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data
