# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .alert_evidence_kind import AlertEvidenceKind
from .alert_monitor import AlertMonitor
from .alert_tracker import AlertTracker


class Alert(UniversalBaseModel):
    """
    One delivery of an alert. Each alert uses 25 credits once, however many channels and recipients deliver it.
    """

    id: str = pydantic.Field()
    """
    Alert delivery id.
    """

    tracker_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Id of the tracker (tracked entity) that produced the alert.
    """

    monitor_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Id of the monitor the tracker belongs to. Null for trackers outside a monitor.
    """

    entity_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Public id ("ent_{n}") of the entity that triggered the alert, when recorded. Null on older alerts recorded before entity_id was stored. Resolve the entity through mention_id or the embedded tracker when this is null.
    """

    mention_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Public id ("men_{n}") of the mention or appearance that triggered the alert. Matches the id on /v1/mentions results. Null when not appearance-scoped.
    """

    video_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    YouTube video id (11 characters) of the video that triggered the alert. Null when not media-scoped.
    """

    excerpt_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Id of the active mention excerpt used as mention evidence. Null when the alert was sent before evidence was recorded.
    """

    evidence_kind: typing.Optional[AlertEvidenceKind] = pydantic.Field(default=None)
    """
    Which evidence layer was sent. Null on older alerts.
    """

    channel: str = pydantic.Field()
    """
    Delivery channel. Values: email (sent by email), webhook (POSTed to the configured webhook URL), slack (sent to Slack).
    """

    status: str = pydantic.Field()
    """
    Delivery status. Values: pending (queued for delivery), sent (delivered), failed (delivery failed; see error_message), skipped (delivery intentionally skipped).
    """

    final_status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Terminal status after retries. Null while delivery is still in progress.
    """

    error_message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Error details for failed deliveries. Null unless delivery failed.
    """

    scheduled_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    When delivery was scheduled. Null when delivered immediately.
    """

    sent_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    When the alert was actually sent. Null until delivery succeeds.
    """

    created_at: str = pydantic.Field()
    """
    When the alert was created.
    """

    tracker: AlertTracker = pydantic.Field()
    """
    The tracker the alert belongs to. Fields are null when the tracker was deleted.
    """

    monitor: typing.Optional[AlertMonitor] = pydantic.Field(default=None)
    """
    The monitor the tracker belongs to. Null for trackers outside a monitor.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
