# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CaptionTrack(UniversalBaseModel):
    code: str = pydantic.Field()
    """
    Caption track code, e.g. en or de. Pass it as language to select this track.
    """

    name: str = pydantic.Field()
    """
    Track name as YouTube reports it.
    """

    generated: bool = pydantic.Field()
    """
    True for YouTube automatic captions, false for a track the channel wrote or approved.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
