# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .channel_page_response_channel_info import ChannelPageResponseChannelInfo
from .channel_page_response_entity import ChannelPageResponseEntity
from .channel_page_response_episodes_by_month_item import ChannelPageResponseEpisodesByMonthItem
from .channel_page_response_episodes_item import ChannelPageResponseEpisodesItem
from .channel_page_response_guests_item import ChannelPageResponseGuestsItem
from .channel_page_response_hosts_detailed_item import ChannelPageResponseHostsDetailedItem
from .channel_page_response_organizations_item import ChannelPageResponseOrganizationsItem
from .channel_page_response_products_item import ChannelPageResponseProductsItem
from .channel_page_response_recommendations_summary import ChannelPageResponseRecommendationsSummary
from .channel_page_response_stats import ChannelPageResponseStats
from .channel_page_response_topics_item import ChannelPageResponseTopicsItem
from .exposure_meta import ExposureMeta


class ChannelPageResponse(UniversalBaseModel):
    entity: ChannelPageResponseEntity = pydantic.Field()
    """
    The channel and who owns it.
    """

    hosts: typing.List[str] = pydantic.Field()
    """
    Host names: configured hosts when the channel has them, else discovered ones.
    """

    stats: ChannelPageResponseStats = pydantic.Field()
    """
    Header vitals. Open on every plan.
    """

    channel_info: typing_extensions.Annotated[
        ChannelPageResponseChannelInfo,
        FieldMetadata(alias="channelInfo"),
        pydantic.Field(alias="channelInfo", description="Channel details, some gated by plan."),
    ]
    """
    Channel details, some gated by plan.
    """

    episodes_by_month: typing_extensions.Annotated[
        typing.List[ChannelPageResponseEpisodesByMonthItem],
        FieldMetadata(alias="episodesByMonth"),
        pydantic.Field(
            alias="episodesByMonth",
            description="Videos published per month. Twelve months ending this month, oldest first. Empty when the plan withholds the chart.",
        ),
    ]
    """
    Videos published per month. Twelve months ending this month, oldest first. Empty when the plan withholds the chart.
    """

    topics: typing.List[ChannelPageResponseTopicsItem] = pydantic.Field()
    """
    Topics across the channel, highest count first.
    """

    hosts_detailed: typing.List[ChannelPageResponseHostsDetailedItem] = pydantic.Field()
    """
    Hosts with their details, in the same order as hosts.
    """

    guests: typing.List[ChannelPageResponseGuestsItem] = pydantic.Field()
    """
    Guests who are not hosts, most appearances first.
    """

    organizations: typing.List[ChannelPageResponseOrganizationsItem] = pydantic.Field()
    """
    Organizations mentioned across the channel, most mentions first.
    """

    products: typing.List[ChannelPageResponseProductsItem] = pydantic.Field()
    """
    Products mentioned across the channel, most mentions first.
    """

    episodes: typing.List[ChannelPageResponseEpisodesItem] = pydantic.Field()
    """
    The channel's newest 50 indexed videos. Open on every plan.
    """

    meta: typing_extensions.Annotated[ExposureMeta, FieldMetadata(alias="_meta"), pydantic.Field(alias="_meta")]
    recommendations_summary: ChannelPageResponseRecommendationsSummary = pydantic.Field()
    """
    Sponsor teaser for the channel.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
