# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .channel_sponsors_response_access_gate import ChannelSponsorsResponseAccessGate
from .channel_sponsors_response_access_reason import ChannelSponsorsResponseAccessReason
from .channel_sponsors_response_access_type import ChannelSponsorsResponseAccessType
from .channel_sponsors_response_access_unlock import ChannelSponsorsResponseAccessUnlock


class ChannelSponsorsResponseAccess(UniversalBaseModel):
    """
    The gate that reduced this response. Present only when something was withheld; carries the same code, gate, and unlock an outright refusal would.
    """

    type: ChannelSponsorsResponseAccessType = pydantic.Field()
    """
    The error class. It fixes the HTTP status: invalid_request_error 400, authentication_error 401, quota_exceeded 402, permission_error 403, not_found 404, conflict_error 409, rate_limit_error 429, server_error 500. Switch on it for retry and gate handling.
    """

    code: str = pydantic.Field()
    """
    The specific condition, stable and snake_case; doc_url anchors on it. x-arcmira-codes on this schema lists every code with its type, gate and meaning. The list is open: new codes may appear inside an existing type, so switch on type and gate first.
    """

    reason: typing.Optional[ChannelSponsorsResponseAccessReason] = pydantic.Field(default=None)
    """
    Only on invalid_api_key. no_credential: nothing was sent. invalid: a credential was sent and is unknown or malformed. revoked: the key exists and is no longer usable.
    """

    message: str = pydantic.Field()
    """
    One plain line. Names the fix or the unlock.
    """

    param: typing.Optional[str] = pydantic.Field(default=None)
    """
    The query or body parameter the gate refused, when one did.
    """

    gate: typing.Optional[ChannelSponsorsResponseAccessGate] = pydantic.Field(default=None)
    """
    Which boundary refused. Present on every gate error; switch on it without parsing the message.
    """

    unlock: typing.Optional[ChannelSponsorsResponseAccessUnlock] = pydantic.Field(default=None)
    """
    How to lift the gate. Present when the gate has an unlock.
    """

    retry_after_seconds: typing.Optional[int] = pydantic.Field(default=None)
    """
    Present on rate gates. Mirrors the Retry-After header.
    """

    current_revision: typing.Optional[str] = pydantic.Field(default=None)
    """
    On revision_mismatch and anchor_mismatch, the transcript revision to re-read before re-anchoring the correction.
    """

    expected_seq: typing.Optional[int] = pydantic.Field(default=None)
    """
    On sequence_mismatch (HTTP 412), the seq the server expects next for this video. Rebase local counters onto it and resend under the same key.
    """

    doc_url: str
    request_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
