# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ChannelSponsorsResponseChannel(UniversalBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Public entity id ("ent_{n}") of the channel. Null when the channel has media in the index but no entity record yet.
    """

    youtube_channel_id: str = pydantic.Field()
    """
    YouTube channel id as supplied in the request path.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Channel name. Null when no entity record exists.
    """

    page: typing.Optional[str] = pydantic.Field(default=None)
    """
    The channel's page on arcmira.com, absolute. Null when no channel is known.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
