# This file was auto-generated by Fern from our API Definition.

import typing

ChannelSponsorsResponseAccessGate = typing.Union[
    typing.Literal["rows", "key", "plan", "freshness", "exposure_law", "rate", "pagination"], typing.Any
]
