# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .entity_product_list_response_export_capabilities import EntityProductListResponseExportCapabilities
from .entity_product_list_response_items_item import EntityProductListResponseItemsItem
from .exposure_meta import ExposureMeta


class EntityProductListResponse(UniversalBaseModel):
    items: typing.List[EntityProductListResponseItemsItem] = pydantic.Field()
    """
    Products related to the entity, highest count first by default. For an organization these are the products it owns that share media with it; for other types, products that co-occur in indexed media.
    """

    total: int = pydantic.Field()
    """
    Rows matching the filter across all pages.
    """

    offset: int = pydantic.Field()
    """
    Row offset of this page, as the cursor encoded it. 0 on the first page.
    """

    limit: int = pydantic.Field()
    """
    Page size applied, after the plan clamp.
    """

    has_more: bool = pydantic.Field()
    """
    True when more rows exist past this page.
    """

    next_cursor: typing.Optional[str] = pydantic.Field(default=None)
    """
    Opaque cursor for the next page. Null on the last page.
    """

    export_capabilities: typing_extensions.Annotated[
        EntityProductListResponseExportCapabilities,
        FieldMetadata(alias="exportCapabilities"),
        pydantic.Field(
            alias="exportCapabilities",
            description="Which orderings and filters this list can serve right now. A list served from a stored top-N serves only the highest counts.",
        ),
    ]
    """
    Which orderings and filters this list can serve right now. A list served from a stored top-N serves only the highest counts.
    """

    meta: typing_extensions.Annotated[ExposureMeta, FieldMetadata(alias="_meta"), pydantic.Field(alias="_meta")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
