# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .entity import Entity
from .entity_detail_recommendations_summary import EntityDetailRecommendationsSummary


class EntityDetailResponse(UniversalBaseModel):
    entity: Entity
    recommendations_summary: typing.Optional[EntityDetailRecommendationsSummary] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
