# This file was auto-generated by Fern from our API Definition.

import typing

EntityResolveResponseConfidence = typing.Union[
    typing.Literal["exact", "single_fuzzy", "ambiguous", "fuzzy", "none"], typing.Any
]
