# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .entity_card import EntityCard


class EntityCardsResponse(UniversalBaseModel):
    cards: typing.List[EntityCard] = pydantic.Field()
    """
    One card per requested id that resolved to an entity, in requested order. Unknown ids are silently dropped.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
