# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class EntityChannelListResponseExportCapabilities(UniversalBaseModel):
    """
    Which orderings and filters this list can serve right now. A list served from a stored top-N serves only the highest counts.
    """

    highest_count: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="highestCount"),
        pydantic.Field(
            alias="highestCount", description="Always true: the highest-count ordering is always available."
        ),
    ]
    """
    Always true: the highest-count ordering is always available.
    """

    lowest_count: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="lowestCount"),
        pydantic.Field(alias="lowestCount", description="True when the lowest-count ordering is available."),
    ]
    """
    True when the lowest-count ordering is available.
    """

    alternate_sort: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="alternateSort"),
        pydantic.Field(alias="alternateSort", description="True when sort keys other than count are available."),
    ]
    """
    True when sort keys other than count are available.
    """

    search: bool = pydantic.Field()
    """
    True when the q filter is available.
    """

    available_rows: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="availableRows"),
        pydantic.Field(
            alias="availableRows",
            description="Present only when a stored top-N is smaller than the full result set: the rows it holds.",
        ),
    ] = None
    """
    Present only when a stored top-N is smaller than the full result set: the rows it holds.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
