# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class EntityDetailRecommendationsSummary(UniversalBaseModel):
    """
    Commercial-intelligence rollup. Only present for organization and product entities when the caller has Recommendations API access (a Pro+ plan) and a brand profile exists.
    """

    total_ad_reads: int = pydantic.Field()
    """
    Total ad_read rows across all channels. 0 when none.
    """

    total_endorsements: int = pydantic.Field()
    """
    Total endorsement rows across all channels. 0 when none.
    """

    unique_shows: int = pydantic.Field()
    """
    Number of distinct shows/channels with commercial mentions of this entity.
    """

    first_seen_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    Timestamp of the earliest commercial mention. Null until the brand profile has been computed.
    """

    last_seen_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    Timestamp of the most recent commercial mention. Null until the brand profile has been computed.
    """

    channels_as_sponsor: int = pydantic.Field()
    """
    Number of channels where this entity appears in the curated known-advertisers dataset.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
