# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .entity_search_result import EntitySearchResult


class EntitySearchResponse(UniversalBaseModel):
    data: typing.List[EntitySearchResult]
    query: str = pydantic.Field()
    """
    The q parameter echoed back.
    """

    has_more: bool = pydantic.Field()
    """
    True when more rows matched than limit. There is no cursor; narrow q or pass type.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
