# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .entity_product_list_response_items_item_sentiment import EntityProductListResponseItemsItemSentiment


class EntityProductListResponseItemsItem(UniversalBaseModel):
    id: int = pydantic.Field()
    """
    Raw integer entity id of the product.
    """

    name: str = pydantic.Field()
    """
    Product name.
    """

    type: str = pydantic.Field()
    """
    Stored entity type. Always product.
    """

    count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Distinct media shared with the entity. Null when the plan hides counts (_meta.showingFullData false).
    """

    avg_sentiment: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="avgSentiment"),
        pydantic.Field(
            alias="avgSentiment",
            description="Raw average sentiment score between -1 and 1. Null when no score was computed.",
        ),
    ] = None
    """
    Raw average sentiment score between -1 and 1. Null when no score was computed.
    """

    sentiment: EntityProductListResponseItemsItemSentiment = pydantic.Field()
    """
    Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score).
    """

    image_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="imageUrl"),
        pydantic.Field(alias="imageUrl", description="Product logo URL. Null until an image has been resolved."),
    ] = None
    """
    Product logo URL. Null until an image has been resolved.
    """

    image_checked_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="imageCheckedAt"),
        pydantic.Field(
            alias="imageCheckedAt", description="When the image pipeline last checked this entity. Null until checked."
        ),
    ] = None
    """
    When the image pipeline last checked this entity. Null until checked.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
