# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .entity_page_mention_excerpt import EntityPageMentionExcerpt
from .entity_page_mention_platform import EntityPageMentionPlatform
from .entity_page_mention_sentiment import EntityPageMentionSentiment
from .entity_page_mention_type import EntityPageMentionType


class EntityPageMention(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Raw appearance row id (the first row for the video), as a string.
    """

    date: str = pydantic.Field()
    """
    Publish date as locale display text, or Unknown.
    """

    published_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="publishedAt"),
        pydantic.Field(alias="publishedAt", description="Publish timestamp. Null when unknown."),
    ] = None
    """
    Publish timestamp. Null when unknown.
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Video title.
    """

    channel: str = pydantic.Field()
    """
    Source channel name, or Unknown Channel.
    """

    channel_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="channelId"),
        pydantic.Field(alias="channelId", description="YouTube channel id of the source channel. Null when unknown."),
    ] = None
    """
    YouTube channel id of the source channel. Null when unknown.
    """

    channel_handle: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="channelHandle"),
        pydantic.Field(alias="channelHandle", description="YouTube handle of the source channel. Null when unknown."),
    ] = None
    """
    YouTube handle of the source channel. Null when unknown.
    """

    platform: EntityPageMentionPlatform = pydantic.Field()
    """
    Always youtube.
    """

    thumbnail: str = pydantic.Field()
    """
    Video thumbnail URL.
    """

    thumbnail_url: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="thumbnailUrl"),
        pydantic.Field(alias="thumbnailUrl", description="Video thumbnail URL. Same value as thumbnail."),
    ]
    """
    Video thumbnail URL. Same value as thumbnail.
    """

    video_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="videoId"),
        pydantic.Field(alias="videoId", description="YouTube video id (11 characters)."),
    ]
    """
    YouTube video id (11 characters).
    """

    duration: typing.Optional[float] = pydantic.Field(default=None)
    """
    Video length in seconds. Null when unknown.
    """

    type: EntityPageMentionType = pydantic.Field()
    """
    Always mention.
    """

    context: str = pydantic.Field()
    """
    Description of the mention, or "No description available".
    """

    sentiment: typing.Optional[EntityPageMentionSentiment] = pydantic.Field(default=None)
    """
    Average sentiment label. Values: positive (average above 0.2), negative (below -0.2), neutral (otherwise, or no score). Absent when no mention in the video carries a score.
    """

    timestamp: typing.Optional[str] = pydantic.Field(default=None)
    """
    Earliest mention timestamp as MM:SS text. Null when the mention covers the full episode.
    """

    raw_timestamp: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="rawTimestamp"),
        pydantic.Field(alias="rawTimestamp", description="Earliest mention timestamp as stored. Null when none."),
    ] = None
    """
    Earliest mention timestamp as stored. Null when none.
    """

    mention_count: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="mentionCount"),
        pydantic.Field(alias="mentionCount", description="Mentions of the entity in this video. At least 1."),
    ]
    """
    Mentions of the entity in this video. At least 1.
    """

    all_timestamps: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="allTimestamps"),
        pydantic.Field(
            alias="allTimestamps",
            description="Every non-zero mention timestamp in the video, as MM:SS text. Absent when there are none.",
        ),
    ] = None
    """
    Every non-zero mention timestamp in the video, as MM:SS text. Absent when there are none.
    """

    excerpt: typing.Optional[EntityPageMentionExcerpt] = pydantic.Field(default=None)
    """
    A speakerless excerpt naming the entity in this media, when one is active.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
