# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from .error_quote_charge import ErrorQuoteCharge
from .transcript_quote import TranscriptQuote


class ErrorQuote(TranscriptQuote):
    """
    The refused price, on a priced refusal: quota_exceeded, max_rows_exceeded, max_charge_exceeded, spend_limit_exceeded, purchase_authority_changed and paid_plan_required.
    """

    charge: typing.Optional[ErrorQuoteCharge] = pydantic.Field(default=None)
    """
    What the purchase would charge at the current balance. Absent when no current price could be read.
    """

    max_on_demand_cents: typing.Optional[int] = pydantic.Field(default=None)
    """
    The money ceiling the current quote needs, in whole cents. Send at least this as max_on_demand_cents with a new intent.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
