# This file was auto-generated by Fern from our API Definition.

import typing

ErrorResourceCommercialWhat = typing.Union[
    typing.Literal["sponsors", "recommendations", "mention_details", "community_review", "paid_split"], typing.Any
]
