# This file was auto-generated by Fern from our API Definition.

import typing

ErrorResourceKeyScope = typing.Union[
    typing.Literal["read", "monitors:write", "trackers:write", "recommendations:read"], typing.Any
]
