# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .error_error import ErrorError
from .error_quote import ErrorQuote


class Error(UniversalBaseModel):
    quote: typing.Optional[ErrorQuote] = pydantic.Field(default=None)
    """
    The refused price, on a priced refusal: quota_exceeded, max_rows_exceeded, max_charge_exceeded, spend_limit_exceeded, purchase_authority_changed and paid_plan_required.
    """

    existing_request_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    On max_charge_exceeded: the accepted purchase for this video that holds a higher money ceiling. Poll it at /v1/transcriptions/{id} instead of starting another.
    """

    existing_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="existingId"),
        pydantic.Field(
            alias="existingId",
            description="On tracker_already_exists, the existing tracker id. Reuse it instead of creating another tracker.",
        ),
    ] = None
    """
    On tracker_already_exists, the existing tracker id. Reuse it instead of creating another tracker.
    """

    error: ErrorError

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
