# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ExposureMetaAccessRowsEntities(UniversalBaseModel):
    """
    People, organization, product, and channel sidebar rows.
    """

    served: int = pydantic.Field()
    """
    Rows the backend returns for this section.
    """

    visible: int = pydantic.Field()
    """
    Rows the site paints unobscured.
    """

    placeholders: int = pydantic.Field()
    """
    Blurred rows the site paints after the visible ones.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
