# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .exposure_meta_access import ExposureMetaAccess
from .exposure_meta_free_limit import ExposureMetaFreeLimit
from .exposure_meta_limit_action import ExposureMetaLimitAction
from .exposure_meta_limits import ExposureMetaLimits
from .exposure_meta_recent_preview import ExposureMetaRecentPreview
from .exposure_meta_recent_preview_mentions import ExposureMetaRecentPreviewMentions
from .exposure_meta_totals import ExposureMetaTotals
from .exposure_meta_usage_limit_type import ExposureMetaUsageLimitType


class ExposureMeta(UniversalBaseModel):
    """
    Usage, plan limits, and the access block for this response: what the caller's plan served and what it withheld.
    """

    tier: str = pydantic.Field()
    """
    Plan tier of the caller. Values: anonymous, free, hobby, pro, pro_plus, ultra, teams, enterprise.
    """

    is_authenticated: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="isAuthenticated"),
        pydantic.Field(alias="isAuthenticated", description="True when the request carried a valid credential."),
    ]
    """
    True when the request carried a valid credential.
    """

    rows_used: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="rowsUsed"),
        pydantic.Field(alias="rowsUsed", description="Rows consumed this period, or lifetime rows on the free tier."),
    ]
    """
    Rows consumed this period, or lifetime rows on the free tier.
    """

    rows_remaining: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="rowsRemaining"),
        pydantic.Field(
            alias="rowsRemaining", description="Rows left this period, or lifetime rows left on the free tier."
        ),
    ]
    """
    Rows left this period, or lifetime rows left on the free tier.
    """

    monthly_rows: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="monthlyRows"),
        pydantic.Field(
            alias="monthlyRows", description="Rows included per period, or the lifetime allocation on the free tier."
        ),
    ]
    """
    Rows included per period, or the lifetime allocation on the free tier.
    """

    is_over_limit: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="isOverLimit"),
        pydantic.Field(alias="isOverLimit", description="True when rowsUsed has reached monthlyRows."),
    ]
    """
    True when rowsUsed has reached monthlyRows.
    """

    on_demand_enabled: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="onDemandEnabled"),
        pydantic.Field(
            alias="onDemandEnabled", description="True when on-demand usage past the included rows is enabled."
        ),
    ]
    """
    True when on-demand usage past the included rows is enabled.
    """

    spend_limit_cents: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="spendLimitCents"),
        pydantic.Field(alias="spendLimitCents", description="On-demand spend limit in US cents. 0 means unlimited."),
    ]
    """
    On-demand spend limit in US cents. 0 means unlimited.
    """

    current_spend_cents: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="currentSpendCents"),
        pydantic.Field(alias="currentSpendCents", description="On-demand spend so far this period, in US cents."),
    ]
    """
    On-demand spend so far this period, in US cents.
    """

    can_continue: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="canContinue"),
        pydantic.Field(alias="canContinue", description="True when the caller can keep reading data right now."),
    ]
    """
    True when the caller can keep reading data right now.
    """

    showing_full_data: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="showingFullData"),
        pydantic.Field(
            alias="showingFullData",
            description="True when the plan serves full data. False when the response is a preview: counts are null and lists are cut.",
        ),
    ]
    """
    True when the plan serves full data. False when the response is a preview: counts are null and lists are cut.
    """

    usage_limit_type: typing_extensions.Annotated[
        ExposureMetaUsageLimitType,
        FieldMetadata(alias="usageLimitType"),
        pydantic.Field(
            alias="usageLimitType",
            description="lifetime on the free tier, whose rows never reset. monthly on paid tiers.",
        ),
    ]
    """
    lifetime on the free tier, whose rows never reset. monthly on paid tiers.
    """

    lifetime_rows_used: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="lifetimeRowsUsed"),
        pydantic.Field(
            alias="lifetimeRowsUsed", description="Free tier only: lifetime rows used. Absent on paid tiers."
        ),
    ] = None
    """
    Free tier only: lifetime rows used. Absent on paid tiers.
    """

    lifetime_rows_allocated: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="lifetimeRowsAllocated"),
        pydantic.Field(
            alias="lifetimeRowsAllocated", description="Free tier only: lifetime rows allocated. Absent on paid tiers."
        ),
    ] = None
    """
    Free tier only: lifetime rows allocated. Absent on paid tiers.
    """

    limit_action: typing_extensions.Annotated[
        typing.Optional[ExposureMetaLimitAction],
        FieldMetadata(alias="limitAction"),
        pydantic.Field(
            alias="limitAction",
            description="Present only when the caller is over the limit and cannot continue. Names the fix: upgrade_to_pro, upgrade_or_enable_ondemand, upgrade_or_increase_limit, enable_ondemand, increase_limit, or contact_sales.",
        ),
    ] = None
    """
    Present only when the caller is over the limit and cannot continue. Names the fix: upgrade_to_pro, upgrade_or_enable_ondemand, upgrade_or_increase_limit, enable_ondemand, increase_limit, or contact_sales.
    """

    limit_message: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="limitMessage"),
        pydantic.Field(
            alias="limitMessage", description="Human sentence for the limit banner. Present only alongside limitAction."
        ),
    ] = None
    """
    Human sentence for the limit banner. Present only alongside limitAction.
    """

    limit_cta_href: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="limitCtaHref"),
        pydantic.Field(
            alias="limitCtaHref",
            description="Site path for the limit banner button. Present only alongside limitAction.",
        ),
    ] = None
    """
    Site path for the limit banner button. Present only alongside limitAction.
    """

    limit_upgrade_tier: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="limitUpgradeTier"),
        pydantic.Field(
            alias="limitUpgradeTier",
            description="The next tier that lifts the limit. Present only alongside limitAction when an upgrade exists. Values: anonymous, free, hobby, pro, pro_plus, ultra, teams, enterprise.",
        ),
    ] = None
    """
    The next tier that lifts the limit. Present only alongside limitAction when an upgrade exists. Values: anonymous, free, hobby, pro, pro_plus, ultra, teams, enterprise.
    """

    limit_upgrade_tier_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="limitUpgradeTierName"),
        pydantic.Field(alias="limitUpgradeTierName", description="Display name of limitUpgradeTier."),
    ] = None
    """
    Display name of limitUpgradeTier.
    """

    totals: ExposureMetaTotals = pydantic.Field()
    """
    True totals behind the returned rows. Each response sets only the keys for its own sections.
    """

    limits: ExposureMetaLimits = pydantic.Field()
    """
    Anonymous row limits and the plan's feature flags.
    """

    cost_per_row_cents: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="costPerRowCents"),
        pydantic.Field(
            alias="costPerRowCents",
            description="On-demand price per row in US cents, e.g. 0.4. 0 on tiers without on-demand.",
        ),
    ]
    """
    On-demand price per row in US cents, e.g. 0.4. 0 on tiers without on-demand.
    """

    is_overage: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="isOverage"),
        pydantic.Field(
            alias="isOverage", description="True when this request billed rows past the included allowance."
        ),
    ]
    """
    True when this request billed rows past the included allowance.
    """

    free_limit: typing_extensions.Annotated[
        ExposureMetaFreeLimit,
        FieldMetadata(alias="freeLimit"),
        pydantic.Field(alias="freeLimit", description="The anonymous row limits again, under their older key."),
    ]
    """
    The anonymous row limits again, under their older key.
    """

    recent_preview: typing_extensions.Annotated[
        typing.Optional[ExposureMetaRecentPreview],
        FieldMetadata(alias="recentPreview"),
        pydantic.Field(
            alias="recentPreview",
            description="Present when the plan withholds the newest media: how much is hidden and a few safe teaser rows.",
        ),
    ] = None
    """
    Present when the plan withholds the newest media: how much is hidden and a few safe teaser rows.
    """

    recent_preview_mentions: typing_extensions.Annotated[
        typing.Optional[ExposureMetaRecentPreviewMentions],
        FieldMetadata(alias="recentPreviewMentions"),
        pydantic.Field(
            alias="recentPreviewMentions", description="Person pages only: the same band for the mentions list."
        ),
    ] = None
    """
    Person pages only: the same band for the mentions list.
    """

    access: ExposureMetaAccess = pydantic.Field()
    """
    Structured access block: what the plan served and what it withheld.
    """

    dc: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="_dc"),
        pydantic.Field(
            alias="_dc",
            description="Delivery class code the freshness filter ran at. Present only when the plan delays media and the response went through that filter.",
        ),
    ] = None
    """
    Delivery class code the freshness filter ran at. Present only when the plan delays media and the response went through that filter.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
