# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .entity_ref import EntityRef
from .mention_media import MentionMedia
from .mention_recommendations import MentionRecommendations
from .mention_sentiment import MentionSentiment


class Mention(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Public mention id in the form "men_{n}".
    """

    entity: EntityRef
    media: MentionMedia
    start_seconds: typing.Optional[int] = pydantic.Field(default=None)
    """
    Start position in the video in integer seconds. 0 means "full episode / no specific moment". Null when the analyzer could not place it in time.
    """

    end_seconds: typing.Optional[int] = pydantic.Field(default=None)
    """
    End position in the video in integer seconds. 0 means "full episode / no specific moment". Null when the analyzer could not place it in time.
    """

    is_appearance: bool = pydantic.Field()
    """
    True when the person physically appears/speaks in the media (person entities only). Always false for organization, product, topic, and channel entities. Filtering with is_appearance=true on a non-person entity returns a 400 (appearances_person_only).
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    One-sentence description of the mention context. Null when not generated.
    """

    confidence: typing.Optional[float] = pydantic.Field(default=None)
    """
    Analyzer confidence between 0 and 1. Null for legacy rows analyzed before confidence scoring.
    """

    sentiment_score: typing.Optional[float] = pydantic.Field(default=None)
    """
    Raw sentiment score between -1 and 1. Null when sentiment was not computed for this mention.
    """

    sentiment: MentionSentiment = pydantic.Field()
    """
    Derived sentiment label from sentiment_score. Values: positive (score above 0.2), negative (score below -0.2), neutral (score between -0.2 and 0.2 inclusive, or no score computed).
    """

    referenced_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    URL referenced in the mention. Null unless one was extracted.
    """

    referenced_platform: typing.Optional[str] = pydantic.Field(default=None)
    """
    Platform referenced in the mention, e.g. "twitter". Null unless one was extracted.
    """

    extracted_content: typing.Optional[str] = pydantic.Field(default=None)
    """
    Verbatim content extracted for the mention. Null unless extraction ran.
    """

    recommendations: typing.Optional[MentionRecommendations] = pydantic.Field(default=None)
    """
    Only present when the request used details=full (requires a Pro+ plan).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
