# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class MergeSuggestionChange(UniversalBaseModel):
    """
    For issue_type merge_suggestion (and duplicate_entity): the canonical merge you are proposing. Provide ids when you have them, names otherwise.
    """

    source_entity_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Public id ("ent_{n}") of the duplicate/variant entity to merge away.
    """

    target_entity_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Public id ("ent_{n}") of the canonical entity to merge into.
    """

    source_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the duplicate entity when you do not have its id.
    """

    merge_into: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name or public id of the canonical entity when you do not have target_entity_id.
    """

    scope_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Scope of the merge rule, e.g. "global".
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
