# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class MissedAlertChange(UniversalBaseModel):
    """
    For issue_type missed_alert: an expectation with no alert to target. Omit the correction id and describe where the alert should have fired.
    """

    source_url: str = pydantic.Field()
    """
    URL of the media that should have produced an alert.
    """

    approximate_timestamp_seconds: typing.Optional[float] = pydantic.Field(default=None)
    """
    Approximate position of the missed occurrence, in seconds from the start of the media.
    """

    entity_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Public id ("ent_{n}") of the tracked entity the missed alert concerns.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
