# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .monitor_access import MonitorAccess
from .monitor_email_recipients_item import MonitorEmailRecipientsItem
from .monitor_team import MonitorTeam


class Monitor(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Monitor id.
    """

    name: str = pydantic.Field()
    """
    Monitor name.
    """

    paused: bool = pydantic.Field()
    """
    True when delivery is paused for all trackers in this monitor. New alerts are not queued, and queued email delivery checks the pause state again before sending. Use PATCH /v1/trackers/{id} with paused: true to pause one tracker.
    """

    notify_emails: typing.List[str] = pydantic.Field()
    """
    Configured email recipients. External recipients must confirm before delivery. Free includes one additional recipient per monitor.
    """

    email_recipients: typing.Optional[typing.List[MonitorEmailRecipientsItem]] = pydantic.Field(default=None)
    """
    Every address the monitor reaches, with consent and invitation state. An account is not required to accept.
    """

    notify_frequency: typing.Optional[str] = pydantic.Field(default=None)
    """
    Delivery cadence. Values: realtime (deliver immediately), hourly (hourly digest), daily (daily digest). Free tier is limited to daily.
    """

    digest_day: typing.Optional[str] = pydantic.Field(default=None)
    """
    Day of week for digest delivery.
    """

    digest_time: typing.Optional[str] = pydantic.Field(default=None)
    """
    Time of day (HH:MM) for digest delivery.
    """

    notify_webhook: bool = pydantic.Field()
    """
    True when webhook delivery is enabled.
    """

    webhook_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Webhook destination URL. Null when no webhook is configured. Absent when access is member: only the team owner sees the webhook.
    """

    webhook_secret_set: typing.Optional[bool] = pydantic.Field(default=None)
    """
    True when a webhook signing secret exists for this monitor. The secret itself is never returned on reads; enablement and rotation responses support recovery with the original Idempotency-Key during the valid recovery window. Absent when access is member.
    """

    webhook_secret_hint: typing.Optional[str] = pydantic.Field(default=None)
    """
    Last 4 characters of the current signing secret, for identifying which secret you hold. Null until a secret exists. Absent when access is member.
    """

    webhook_failures: typing.Optional[int] = pydantic.Field(default=None)
    """
    Consecutive webhook delivery failures recorded for this monitor. Reset by a secret rotation or PATCHing notify_webhook: true; 10 consecutive failures auto-disable a webhook. Note: the delivery pipeline currently accrues failures on the tracker that fired, so this monitor-level counter can lag.
    """

    webhook_disabled_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    When the webhook was auto-disabled after repeated failures. Null while delivery is enabled. Re-enable by PATCHing notify_webhook: true; rotation alone never re-enables.
    """

    webhook_disabled_reason: typing.Optional[str] = pydantic.Field(default=None)
    """
    Why the webhook was auto-disabled. Null while delivery is enabled.
    """

    notify_slack: bool = pydantic.Field()
    """
    True when Slack delivery is enabled.
    """

    slack_integration_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Slack integration used for delivery. Null when Slack is not configured.
    """

    slack_channel_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Slack channel to deliver to. Null when Slack is not configured.
    """

    created_at: str = pydantic.Field()
    """
    When the monitor was created.
    """

    updated_at: str = pydantic.Field()
    """
    When the monitor was last updated.
    """

    team: typing.Optional[MonitorTeam] = pydantic.Field(default=None)
    """
    The team the monitor is shared with. Null for a personal monitor.
    """

    access: MonitorAccess = pydantic.Field()
    """
    account: the caller pays for the monitor, as its personal owner or the team owner. member: the caller is another member of its team, who may edit it but not its webhook, and may not delete it.
    """

    muted: bool = pydantic.Field()
    """
    True when the caller muted this team monitor for themselves. Always false on a personal monitor.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
