# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .monitor_email_recipients_item import MonitorEmailRecipientsItem


class Monitor(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Monitor id.
    """

    name: str = pydantic.Field()
    """
    Monitor name.
    """

    is_collapsed: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="isCollapsed"),
        pydantic.Field(alias="isCollapsed", description="True when the monitor is collapsed in the dashboard UI."),
    ]
    """
    True when the monitor is collapsed in the dashboard UI.
    """

    is_paused: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="isPaused"),
        pydantic.Field(
            alias="isPaused",
            description="True when delivery is paused for all trackers in this monitor. New alerts are not queued, and queued email delivery checks the pause state again before sending. Use PATCH /v1/trackers/{id} with paused: true to pause one tracker.",
        ),
    ]
    """
    True when delivery is paused for all trackers in this monitor. New alerts are not queued, and queued email delivery checks the pause state again before sending. Use PATCH /v1/trackers/{id} with paused: true to pause one tracker.
    """

    sort_order: typing_extensions.Annotated[
        int, FieldMetadata(alias="sortOrder"), pydantic.Field(alias="sortOrder", description="Dashboard sort position.")
    ]
    """
    Dashboard sort position.
    """

    notify_emails: typing_extensions.Annotated[
        typing.List[str],
        FieldMetadata(alias="notifyEmails"),
        pydantic.Field(
            alias="notifyEmails",
            description="Configured email recipients. External recipients must confirm before delivery. Free includes one additional recipient per monitor.",
        ),
    ]
    """
    Configured email recipients. External recipients must confirm before delivery. Free includes one additional recipient per monitor.
    """

    email_recipients: typing_extensions.Annotated[
        typing.Optional[typing.List[MonitorEmailRecipientsItem]],
        FieldMetadata(alias="emailRecipients"),
        pydantic.Field(
            alias="emailRecipients",
            description="Recipient consent and invitation state. An account is not required to accept.",
        ),
    ] = None
    """
    Recipient consent and invitation state. An account is not required to accept.
    """

    notify_frequency: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="notifyFrequency"),
        pydantic.Field(
            alias="notifyFrequency",
            description="Delivery cadence. Values: realtime (deliver immediately), hourly (hourly digest), daily (daily digest). Free tier is limited to daily.",
        ),
    ] = None
    """
    Delivery cadence. Values: realtime (deliver immediately), hourly (hourly digest), daily (daily digest). Free tier is limited to daily.
    """

    digest_day: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="digestDay"),
        pydantic.Field(alias="digestDay", description="Day of week for digest delivery."),
    ] = None
    """
    Day of week for digest delivery.
    """

    digest_time: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="digestTime"),
        pydantic.Field(alias="digestTime", description="Time of day (HH:MM) for digest delivery."),
    ] = None
    """
    Time of day (HH:MM) for digest delivery.
    """

    notify_webhook: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="notifyWebhook"),
        pydantic.Field(alias="notifyWebhook", description="True when webhook delivery is enabled."),
    ]
    """
    True when webhook delivery is enabled.
    """

    webhook_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="webhookUrl"),
        pydantic.Field(alias="webhookUrl", description="Webhook destination URL. Null when no webhook is configured."),
    ] = None
    """
    Webhook destination URL. Null when no webhook is configured.
    """

    webhook_secret_set: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="webhookSecretSet"),
        pydantic.Field(
            alias="webhookSecretSet",
            description="True when a webhook signing secret exists for this monitor. The secret itself is never returned on reads; it is returned exactly once at enablement or rotation.",
        ),
    ]
    """
    True when a webhook signing secret exists for this monitor. The secret itself is never returned on reads; it is returned exactly once at enablement or rotation.
    """

    webhook_secret_hint: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="webhookSecretHint"),
        pydantic.Field(
            alias="webhookSecretHint",
            description="Last 4 characters of the current signing secret, for identifying which secret you hold. Null until a secret exists.",
        ),
    ] = None
    """
    Last 4 characters of the current signing secret, for identifying which secret you hold. Null until a secret exists.
    """

    webhook_failures: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="webhookFailures"),
        pydantic.Field(
            alias="webhookFailures",
            description="Consecutive webhook delivery failures recorded for this monitor. Reset by a secret rotation or PATCHing notifyWebhook: true; 10 consecutive failures auto-disable a webhook. Note: the delivery pipeline currently accrues failures on the tracker that fired, so this monitor-level counter can lag.",
        ),
    ] = None
    """
    Consecutive webhook delivery failures recorded for this monitor. Reset by a secret rotation or PATCHing notifyWebhook: true; 10 consecutive failures auto-disable a webhook. Note: the delivery pipeline currently accrues failures on the tracker that fired, so this monitor-level counter can lag.
    """

    webhook_disabled_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="webhookDisabledAt"),
        pydantic.Field(
            alias="webhookDisabledAt",
            description="When the webhook was auto-disabled after repeated failures. Null while delivery is enabled. Re-enable by PATCHing notifyWebhook: true; rotation alone never re-enables.",
        ),
    ] = None
    """
    When the webhook was auto-disabled after repeated failures. Null while delivery is enabled. Re-enable by PATCHing notifyWebhook: true; rotation alone never re-enables.
    """

    webhook_disabled_reason: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="webhookDisabledReason"),
        pydantic.Field(
            alias="webhookDisabledReason",
            description="Why the webhook was auto-disabled. Null while delivery is enabled.",
        ),
    ] = None
    """
    Why the webhook was auto-disabled. Null while delivery is enabled.
    """

    notify_slack: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="notifySlack"),
        pydantic.Field(alias="notifySlack", description="True when Slack delivery is enabled."),
    ]
    """
    True when Slack delivery is enabled.
    """

    slack_integration_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="slackIntegrationId"),
        pydantic.Field(
            alias="slackIntegrationId",
            description="Slack integration used for delivery. Null when Slack is not configured.",
        ),
    ] = None
    """
    Slack integration used for delivery. Null when Slack is not configured.
    """

    slack_channel_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="slackChannelId"),
        pydantic.Field(
            alias="slackChannelId", description="Slack channel to deliver to. Null when Slack is not configured."
        ),
    ] = None
    """
    Slack channel to deliver to. Null when Slack is not configured.
    """

    created_at: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When the monitor was created."),
    ]
    """
    When the monitor was created.
    """

    updated_at: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="updatedAt"),
        pydantic.Field(alias="updatedAt", description="When the monitor was last updated."),
    ]
    """
    When the monitor was last updated.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
