# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from .monitor import Monitor


class MonitorMutationResponseMonitor(Monitor):
    tracker_count: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="trackerCount"),
        pydantic.Field(
            alias="trackerCount", description="Number of trackers in the monitor. Always 0 in the create response."
        ),
    ]
    """
    Number of trackers in the monitor. Always 0 in the create response.
    """

    webhook_secret: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="webhookSecret"),
        pydantic.Field(
            alias="webhookSecret",
            description='The webhook signing secret ("whsec_..."). Only present when this request NEWLY enabled webhook signing: a create with notifyWebhook: true and a webhookUrl, or a PATCH that turns the webhook on (or sets a URL) where no secret existed before. Returned only once. Store it securely; it cannot be retrieved later. To recover from a lost secret, rotate.',
        ),
    ] = None
    """
    The webhook signing secret ("whsec_..."). Only present when this request NEWLY enabled webhook signing: a create with notifyWebhook: true and a webhookUrl, or a PATCH that turns the webhook on (or sets a URL) where no secret existed before. Returned only once. Store it securely; it cannot be retrieved later. To recover from a lost secret, rotate.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
