# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class MonitorListResponseMonitorsItemSlackIntegration(UniversalBaseModel):
    """
    Display metadata for the connected Slack integration. Null/absent when Slack is not configured.
    """

    id: str = pydantic.Field()
    """
    Slack integration id.
    """

    team_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Slack workspace name.
    """

    channel_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Slack channel the integration posts to.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
