# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class OrganizationPageResponseRoleEdgePeopleItem(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    Co-CEO name.
    """

    href: typing.Optional[str] = pydantic.Field(default=None)
    """
    Site-relative link to the co-CEO page. Null when none.
    """

    image_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="imageUrl"),
        pydantic.Field(alias="imageUrl", description="Co-CEO image URL. Null until resolved."),
    ] = None
    """
    Co-CEO image URL. Null until resolved.
    """

    image_checked_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="imageCheckedAt"),
        pydantic.Field(
            alias="imageCheckedAt", description="When the image pipeline last checked this person. Null until checked."
        ),
    ] = None
    """
    When the image pipeline last checked this person. Null until checked.
    """

    true_appearances: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="trueAppearances"),
        pydantic.Field(alias="trueAppearances", description="Media the co-CEO appeared in."),
    ]
    """
    Media the co-CEO appeared in.
    """

    receipt: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display line naming the evidence. Null when there is none to show.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
