# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .entity_page_mention import EntityPageMention
from .exposure_meta import ExposureMeta
from .organization_page_response_channels_item import OrganizationPageResponseChannelsItem
from .organization_page_response_entity import OrganizationPageResponseEntity
from .organization_page_response_mentions_by_month_item import OrganizationPageResponseMentionsByMonthItem
from .organization_page_response_people_item import OrganizationPageResponsePeopleItem
from .organization_page_response_products_item import OrganizationPageResponseProductsItem
from .organization_page_response_role_edge import OrganizationPageResponseRoleEdge
from .organization_page_response_stats import OrganizationPageResponseStats
from .organization_page_response_topics_item import OrganizationPageResponseTopicsItem


class OrganizationPageResponse(UniversalBaseModel):
    entity: OrganizationPageResponseEntity = pydantic.Field()
    """
    The organization and what it owns.
    """

    role_edge: typing_extensions.Annotated[
        typing.Optional[OrganizationPageResponseRoleEdge],
        FieldMetadata(alias="roleEdge"),
        pydantic.Field(
            alias="roleEdge", description="The verified CEO of the organization. Null when none is verified."
        ),
    ] = None
    """
    The verified CEO of the organization. Null when none is verified.
    """

    stats: OrganizationPageResponseStats = pydantic.Field()
    """
    Headline numbers and section totals for the organization.
    """

    mentions_by_month: typing_extensions.Annotated[
        typing.List[OrganizationPageResponseMentionsByMonthItem],
        FieldMetadata(alias="mentionsByMonth"),
        pydantic.Field(
            alias="mentionsByMonth",
            description="Media mentioning the organization per month. Twelve months ending this month, oldest first. Empty when the plan withholds the chart.",
        ),
    ]
    """
    Media mentioning the organization per month. Twelve months ending this month, oldest first. Empty when the plan withholds the chart.
    """

    topics: typing.List[OrganizationPageResponseTopicsItem] = pydantic.Field()
    """
    Co-occurring topics, highest count first.
    """

    people: typing.List[OrganizationPageResponsePeopleItem] = pydantic.Field()
    """
    Co-occurring people, highest count first.
    """

    products: typing.List[OrganizationPageResponseProductsItem] = pydantic.Field()
    """
    Products the organization owns that share media with it, most mentions first.
    """

    channels: typing.List[OrganizationPageResponseChannelsItem] = pydantic.Field()
    """
    Channels that mention the organization, highest count first.
    """

    mentions: typing.List[EntityPageMention] = pydantic.Field()
    """
    Newest media that mention the entity, one row per video, cut to the plan's media rows.
    """

    meta: typing_extensions.Annotated[ExposureMeta, FieldMetadata(alias="_meta"), pydantic.Field(alias="_meta")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
