# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class OrganizationPageResponseStats(UniversalBaseModel):
    """
    Headline numbers and section totals for the organization.
    """

    velocity: typing.Optional[int] = pydantic.Field(default=None)
    """
    Mentions in the last 90 days. Null when the plan hides it.
    """

    sentiment: float = pydantic.Field()
    """
    Reserved. Always 0.
    """

    reach: str = pydantic.Field()
    """
    Total views as display text, e.g. 1.2M.
    """

    reach_raw: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="reachRaw"),
        pydantic.Field(alias="reachRaw", description="Total views of the media that mention the organization."),
    ]
    """
    Total views of the media that mention the organization.
    """

    total: int = pydantic.Field()
    """
    Total media that mention the organization.
    """

    latest_media_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="latestMediaAt"),
        pydantic.Field(
            alias="latestMediaAt",
            description="Newest publish date among the counted media. Null when none. The freshness gate does not withhold it.",
        ),
    ] = None
    """
    Newest publish date among the counted media. Null when none. The freshness gate does not withhold it.
    """

    people: int = pydantic.Field()
    """
    Total co-occurring people.
    """

    topics: int = pydantic.Field()
    """
    Total co-occurring topics.
    """

    products: int = pydantic.Field()
    """
    Owned products with mentions.
    """

    channels: int = pydantic.Field()
    """
    Total channels that mention the organization.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
