# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class PersonPageResponseMentionsByMonthItem(UniversalBaseModel):
    month: str = pydantic.Field()
    """
    Three-letter month name, e.g. Jan.
    """

    year_month: typing_extensions.Annotated[
        str, FieldMetadata(alias="yearMonth"), pydantic.Field(alias="yearMonth", description="The month as YYYY-MM.")
    ]
    """
    The month as YYYY-MM.
    """

    count: int = pydantic.Field()
    """
    Media that month. Months inside the withheld window read 0.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
