# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .refused_quote_charge_from import RefusedQuoteChargeFrom
from .refused_quote_charge_unit import RefusedQuoteChargeUnit


class RefusedQuoteCharge(UniversalBaseModel):
    """
    What the purchase would charge at the current balance. Absent when no current price could be read.
    """

    unit: RefusedQuoteChargeUnit
    amount: float
    from_: typing_extensions.Annotated[
        RefusedQuoteChargeFrom,
        FieldMetadata(alias="from"),
        pydantic.Field(alias="from", description="Where the charge would come from at the current balance."),
    ]
    """
    Where the charge would come from at the current balance.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
