# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SignupVerifiedResponse(UniversalBaseModel):
    key: str = pydantic.Field()
    """
    The arc_sk_ account key. Shown once. Send it as Authorization: Bearer.
    """

    key_id: str = pydantic.Field()
    """
    The key id. Appears on funnel events and in the dashboard; never a secret.
    """

    header: str = pydantic.Field()
    """
    The pasteable request header line: Authorization: Bearer arc_sk_...
    """

    scopes: typing.List[str] = pydantic.Field()
    """
    Always ["read"]. Create an Admin key in the dashboard for account write access.
    """

    tier: str = pydantic.Field()
    """
    The plan the account is on: free for a new account, its plan when the address already had one.
    """

    rows_allotted: int = pydantic.Field()
    """
    The pool this key draws on: a free account's lifetime credits, a paid plan's monthly rows.
    """

    next: str = pydantic.Field()
    """
    A curl command for the first call: GET /v1/me with the key.
    """

    docs_url: str = pydantic.Field()
    """
    Sign-up documentation.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
