# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .slack_integration_list_response_integrations_item import SlackIntegrationListResponseIntegrationsItem


class SlackIntegrationListResponse(UniversalBaseModel):
    integrations: typing.List[SlackIntegrationListResponseIntegrationsItem] = pydantic.Field()
    """
    Active Slack workspaces connected to the account, ordered by workspace name. Empty when none is connected: connect one in the dashboard first.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
