# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class Tracker(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Tracker id in the form "trk_{hex}".
    """

    entity_name: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="entityName"),
        pydantic.Field(alias="entityName", description="The tracked entity name, as submitted."),
    ]
    """
    The tracked entity name, as submitted.
    """

    entity_type: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="entityType"),
        pydantic.Field(
            alias="entityType",
            description="The tracked entity type. Values: person, organization, product, topic, channel.",
        ),
    ]
    """
    The tracked entity type. Values: person, organization, product, topic, channel.
    """

    display_name: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="displayName"),
        pydantic.Field(
            alias="displayName", description="User-facing display name. Falls back to entityName when not customized."
        ),
    ]
    """
    User-facing display name. Falls back to entityName when not customized.
    """

    notify_email: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="notifyEmail"),
        pydantic.Field(
            alias="notifyEmail", description="True when this tracker delivers by email (default true at creation)."
        ),
    ]
    """
    True when this tracker delivers by email (default true at creation).
    """

    notify_webhook: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="notifyWebhook"),
        pydantic.Field(
            alias="notifyWebhook", description="True when this tracker has a per-tracker webhook override enabled."
        ),
    ]
    """
    True when this tracker has a per-tracker webhook override enabled.
    """

    notify_slack: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="notifySlack"),
        pydantic.Field(
            alias="notifySlack", description="True when this tracker has a per-tracker Slack override enabled."
        ),
    ]
    """
    True when this tracker has a per-tracker Slack override enabled.
    """

    webhook_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="webhookUrl"),
        pydantic.Field(
            alias="webhookUrl",
            description="Per-tracker webhook destination override. Null when the tracker uses its monitor's delivery settings.",
        ),
    ] = None
    """
    Per-tracker webhook destination override. Null when the tracker uses its monitor's delivery settings.
    """

    slack_channel_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="slackChannelId"),
        pydantic.Field(alias="slackChannelId", description="Per-tracker Slack channel override. Null when not set."),
    ] = None
    """
    Per-tracker Slack channel override. Null when not set.
    """

    slack_integration_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="slackIntegrationId"),
        pydantic.Field(
            alias="slackIntegrationId", description="Per-tracker Slack integration override. Null when not set."
        ),
    ] = None
    """
    Per-tracker Slack integration override. Null when not set.
    """

    filters: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Optional matching filters as submitted. Null when none were set.
    """

    is_paused: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="isPaused"),
        pydantic.Field(alias="isPaused", description="True when the tracker is paused."),
    ]
    """
    True when the tracker is paused.
    """

    paused_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="pausedAt"),
        pydantic.Field(alias="pausedAt", description="When the tracker was paused. Null unless paused."),
    ] = None
    """
    When the tracker was paused. Null unless paused.
    """

    last_notified_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="lastNotifiedAt"),
        pydantic.Field(
            alias="lastNotifiedAt", description="When the tracker last produced an alert. Null until the first alert."
        ),
    ] = None
    """
    When the tracker last produced an alert. Null until the first alert.
    """

    created_at: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When the tracker was created."),
    ]
    """
    When the tracker was created.
    """

    updated_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="updatedAt"),
        pydantic.Field(alias="updatedAt", description="When the tracker was last updated."),
    ] = None
    """
    When the tracker was last updated.
    """

    monitor_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="monitorId"),
        pydantic.Field(
            alias="monitorId", description="The monitor this tracker belongs to. Absent for standalone trackers."
        ),
    ] = None
    """
    The monitor this tracker belongs to. Absent for standalone trackers.
    """

    email_delivery_count: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="emailDeliveryCount"),
        pydantic.Field(alias="emailDeliveryCount", description="Email deliveries in the current billing period."),
    ]
    """
    Email deliveries in the current billing period.
    """

    webhook_delivery_count: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="webhookDeliveryCount"),
        pydantic.Field(alias="webhookDeliveryCount", description="Webhook deliveries in the current billing period."),
    ]
    """
    Webhook deliveries in the current billing period.
    """

    slack_delivery_count: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="slackDeliveryCount"),
        pydantic.Field(alias="slackDeliveryCount", description="Slack deliveries in the current billing period."),
    ]
    """
    Slack deliveries in the current billing period.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
