# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .transcript_preparation_required_quote_charge_from import TranscriptPreparationRequiredQuoteChargeFrom
from .transcript_preparation_required_quote_charge_unit import TranscriptPreparationRequiredQuoteChargeUnit


class TranscriptPreparationRequiredQuoteCharge(UniversalBaseModel):
    unit: TranscriptPreparationRequiredQuoteChargeUnit
    amount: float = pydantic.Field()
    """
    Credits the purchase would charge.
    """

    from_: typing_extensions.Annotated[
        TranscriptPreparationRequiredQuoteChargeFrom,
        FieldMetadata(alias="from"),
        pydantic.Field(alias="from", description="Where those credits would come from at the current balance."),
    ]
    """
    Where those credits would come from at the current balance.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
