# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .refused_quote import RefusedQuote


class TranscriptResponseAccessDetails(UniversalBaseModel):
    """
    Machine data the refusal carries for you to act on. Present only on the codes that name a field here.
    """

    quote: typing.Optional[RefusedQuote] = None
    existing_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    On tracker_already_exists, the existing tracker id. Reuse it instead of creating another tracker.
    """

    limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    On tracker_limit, the trackers the plan holds.
    """

    count: typing.Optional[int] = pydantic.Field(default=None)
    """
    On tracker_limit, the trackers the account holds now.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
