# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .transcript_edit_submitted_response_edit_status import TranscriptEditSubmittedResponseEditStatus


class TranscriptEditSubmittedResponseEdit(UniversalBaseModel):
    """
    The stored pending edit. It replaces any pending edit you had on the same line.
    """

    id: int = pydantic.Field()
    """
    Pending row id. Withdraw it with DELETE /v1/transcripts/{video_id}/edits/{id}.
    """

    video_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="videoId"),
        pydantic.Field(alias="videoId", description="YouTube video id (11 characters)."),
    ]
    """
    YouTube video id (11 characters).
    """

    segment_index: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="segmentIndex"),
        pydantic.Field(alias="segmentIndex", description="The line index the edit targets."),
    ]
    """
    The line index the edit targets.
    """

    corrected_text: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="correctedText"),
        pydantic.Field(alias="correctedText", description="The corrected line text as stored, trimmed."),
    ]
    """
    The corrected line text as stored, trimmed.
    """

    status: TranscriptEditSubmittedResponseEditStatus = pydantic.Field()
    """
    Review status. Always pending on submit.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
