# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TranscriptQuote(UniversalBaseModel):
    quarters: int = pydantic.Field()
    """
    Number of 15-minute blocks in the video, ceiling'd, minimum 1.
    """

    rows: int = pydantic.Field()
    """
    Rows the whole video uses, 75 rows per 15-minute block.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
