# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .named_entity_ref import NamedEntityRef


class TranscriptSearchChunk(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Search index chunk id. Opaque.
    """

    video_id: str = pydantic.Field()
    """
    YouTube video id (11 characters).
    """

    channel_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    YouTube channel id of the source channel.
    """

    channel_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Source channel name.
    """

    channel_page: typing.Optional[str] = pydantic.Field(default=None)
    """
    The channel's page on arcmira.com, absolute. Null when no channel is known.
    """

    video_title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Video title.
    """

    speakers: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Speaker names identified on this slice, when known.
    """

    source: typing.Optional[str] = pydantic.Field(default=None)
    """
    Transcript source class: arcmira_premium, creator_captions, or third_party_quick.
    """

    source_label: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human label for source.
    """

    published_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    Video publish timestamp. Cite it as the date of the quote.
    """

    text: str = pydantic.Field()
    """
    The spoken slice. Search results include text on every plan within the permitted publication-date window.
    """

    start_seconds: typing.Optional[int] = pydantic.Field(default=None)
    """
    Offset of the slice in the video, in seconds.
    """

    watch_url: str = pydantic.Field()
    """
    Absolute watch URL on arcmira.com with the timestamp, e.g. https://arcmira.com/watch?v=...&t=4787.
    """

    cite_line: typing.Optional[str] = pydantic.Field(default=None)
    """
    A ready citation line: title, clock, channel, date.
    """

    score: float = pydantic.Field()
    """
    Retrieval score. Higher is a closer match. Not comparable across calls.
    """

    about: typing.Optional[typing.List[NamedEntityRef]] = pydantic.Field(default=None)
    """
    Entities the passage is tagged about (excerpt pins, exact-name mentions, ad verdicts). Present on passages served from the spoken index.
    """

    speakers_by: typing.Optional[typing.List[NamedEntityRef]] = pydantic.Field(default=None)
    """
    The people speaking in the passage, as ids with names. Present on passages served from the spoken index.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
