# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TranscriptResponsePremiumJob(UniversalBaseModel):
    """
    Present when you asked for Premium on a video we have not transcribed yet. The captions text is in this same response; poll the job for the Premium one.
    """

    job_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Transcription request id. Poll it with GET /v1/transcriptions/{id}.
    """

    status: str = pydantic.Field()
    """
    Pipeline status at submit time.
    """

    next_poll_seconds: typing.Optional[int] = pydantic.Field(default=None)
    """
    Seconds to wait before polling again.
    """

    eta_seconds: typing.Optional[int] = pydantic.Field(default=None)
    """
    Estimated seconds until the Premium transcript is ready.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
