# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .wrong_classification_change_mention_class import WrongClassificationChangeMentionClass


class WrongClassificationChange(UniversalBaseModel):
    """
    For issue_type wrong_classification: the commercial class the row should carry.
    """

    mention_class: typing.Optional[WrongClassificationChangeMentionClass] = pydantic.Field(default=None)
    """
    The correct commercial classification. Values: ad_read (an ad-style promotion heard at that moment: a paid sponsor read, promo code, affiliate plug, thanks for supplied goods or venue, or a show promoting its own product as an ad), endorsement (an unpaid personal recommendation), mention (a neutral commercial mention).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
