# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.message_response import MessageResponse
from ..types.tracker_list_response import TrackerListResponse
from ..types.tracker_mutation_response import TrackerMutationResponse
from .raw_client import AsyncRawTrackersClient, RawTrackersClient
from .types.update_trackers_request_person_match_mode import UpdateTrackersRequestPersonMatchMode

if typing.TYPE_CHECKING:
    from .alerts.client import AlertsClient, AsyncAlertsClient
# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TrackersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTrackersClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._alerts: typing.Optional[AlertsClient] = None

    @property
    def with_raw_response(self) -> RawTrackersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTrackersClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> TrackerListResponse:
        """
        All trackers for the account, newest first, with per-channel delivery counts for the current billing period. Single page, no pagination.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TrackerListResponse
            Success

        Examples
        --------
        from arcmira import Arcmira

        client = Arcmira(
            api_key="YOUR_API_KEY",
        )
        client.trackers.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def delete(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MessageResponse:
        """
        Deletes the tracker. Cannot be undone. Its monitor stays, with its delivery settings, even when this was its last tracker.

        Parameters
        ----------
        id : str
            Tracker id, trk_ form.

        idempotency_key : typing.Optional[str]
            One key per intent, 1 to 255 printable ASCII characters (0x21 to 0x7E); anything else is 400 invalid_idempotency_key. Keys are scoped to the account, credential and resource family. The same key and normalized method, path and body returns the committed response with Idempotency-Replayed: true. A changed intent within the same family returns 409 idempotency_conflict. Monitor and tracker families have independent namespaces. Secret recovery is limited as described by the operation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageResponse
            Success

        Examples
        --------
        from arcmira import Arcmira

        client = Arcmira(
            api_key="YOUR_API_KEY",
        )
        client.trackers.delete(
            id="id",
            idempotency_key="8b2f6c3e-4d1a-4e7b-9c05-2f6a1b7d3e90",
        )
        """
        _response = self._raw_client.delete(id, idempotency_key=idempotency_key, request_options=request_options)
        return _response.data

    def update(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        display_name: typing.Optional[str] = OMIT,
        person_match_mode: typing.Optional[UpdateTrackersRequestPersonMatchMode] = OMIT,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        paused: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TrackerMutationResponse:
        """
        Partial update: send only the fields to change. The tracked entity itself (entity_name/entity_type) is immutable; delete and recreate to watch a different entity. Delivery is the monitor's: change it with PATCH /v1/monitors/{id}.

        Parameters
        ----------
        id : str
            Tracker id, trk_ form.

        idempotency_key : typing.Optional[str]
            One key per intent, 1 to 255 printable ASCII characters (0x21 to 0x7E); anything else is 400 invalid_idempotency_key. Keys are scoped to the account, credential and resource family. The same key and normalized method, path and body returns the committed response with Idempotency-Replayed: true. A changed intent within the same family returns 409 idempotency_conflict. Monitor and tracker families have independent namespaces. Secret recovery is limited as described by the operation.

        display_name : typing.Optional[str]
            Optional label shown in alerts and the dashboard.

        person_match_mode : typing.Optional[UpdateTrackersRequestPersonMatchMode]
            Person trackers only. Mentions (default) matches others talking about the person; appearances matches the person present as a speaker, host or guest; both accepts either. Non-person trackers reject this field. PATCH changes future and pending delivery eligibility, without backfill.

        filters : typing.Optional[typing.Dict[str, typing.Any]]
            Stored filter object. personMatchMode is also accepted here for person trackers. Other filter keys are retained; do not assume they change matching.

        paused : typing.Optional[bool]
            Pause or resume the tracker. Paused trackers stop producing alerts; there is no backfill for the paused window.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TrackerMutationResponse
            Success

        Examples
        --------
        from arcmira import Arcmira

        client = Arcmira(
            api_key="YOUR_API_KEY",
        )
        client.trackers.update(
            id="id",
            idempotency_key="8b2f6c3e-4d1a-4e7b-9c05-2f6a1b7d3e90",
        )
        """
        _response = self._raw_client.update(
            id,
            idempotency_key=idempotency_key,
            display_name=display_name,
            person_match_mode=person_match_mode,
            filters=filters,
            paused=paused,
            request_options=request_options,
        )
        return _response.data

    @property
    def alerts(self):
        if self._alerts is None:
            from .alerts.client import AlertsClient  # noqa: E402

            self._alerts = AlertsClient(client_wrapper=self._client_wrapper)
        return self._alerts


class AsyncTrackersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTrackersClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._alerts: typing.Optional[AsyncAlertsClient] = None

    @property
    def with_raw_response(self) -> AsyncRawTrackersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTrackersClient
        """
        return self._raw_client

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> TrackerListResponse:
        """
        All trackers for the account, newest first, with per-channel delivery counts for the current billing period. Single page, no pagination.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TrackerListResponse
            Success

        Examples
        --------
        import asyncio

        from arcmira import AsyncArcmira

        client = AsyncArcmira(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.trackers.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def delete(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MessageResponse:
        """
        Deletes the tracker. Cannot be undone. Its monitor stays, with its delivery settings, even when this was its last tracker.

        Parameters
        ----------
        id : str
            Tracker id, trk_ form.

        idempotency_key : typing.Optional[str]
            One key per intent, 1 to 255 printable ASCII characters (0x21 to 0x7E); anything else is 400 invalid_idempotency_key. Keys are scoped to the account, credential and resource family. The same key and normalized method, path and body returns the committed response with Idempotency-Replayed: true. A changed intent within the same family returns 409 idempotency_conflict. Monitor and tracker families have independent namespaces. Secret recovery is limited as described by the operation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageResponse
            Success

        Examples
        --------
        import asyncio

        from arcmira import AsyncArcmira

        client = AsyncArcmira(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.trackers.delete(
                id="id",
                idempotency_key="8b2f6c3e-4d1a-4e7b-9c05-2f6a1b7d3e90",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id, idempotency_key=idempotency_key, request_options=request_options)
        return _response.data

    async def update(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        display_name: typing.Optional[str] = OMIT,
        person_match_mode: typing.Optional[UpdateTrackersRequestPersonMatchMode] = OMIT,
        filters: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        paused: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TrackerMutationResponse:
        """
        Partial update: send only the fields to change. The tracked entity itself (entity_name/entity_type) is immutable; delete and recreate to watch a different entity. Delivery is the monitor's: change it with PATCH /v1/monitors/{id}.

        Parameters
        ----------
        id : str
            Tracker id, trk_ form.

        idempotency_key : typing.Optional[str]
            One key per intent, 1 to 255 printable ASCII characters (0x21 to 0x7E); anything else is 400 invalid_idempotency_key. Keys are scoped to the account, credential and resource family. The same key and normalized method, path and body returns the committed response with Idempotency-Replayed: true. A changed intent within the same family returns 409 idempotency_conflict. Monitor and tracker families have independent namespaces. Secret recovery is limited as described by the operation.

        display_name : typing.Optional[str]
            Optional label shown in alerts and the dashboard.

        person_match_mode : typing.Optional[UpdateTrackersRequestPersonMatchMode]
            Person trackers only. Mentions (default) matches others talking about the person; appearances matches the person present as a speaker, host or guest; both accepts either. Non-person trackers reject this field. PATCH changes future and pending delivery eligibility, without backfill.

        filters : typing.Optional[typing.Dict[str, typing.Any]]
            Stored filter object. personMatchMode is also accepted here for person trackers. Other filter keys are retained; do not assume they change matching.

        paused : typing.Optional[bool]
            Pause or resume the tracker. Paused trackers stop producing alerts; there is no backfill for the paused window.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TrackerMutationResponse
            Success

        Examples
        --------
        import asyncio

        from arcmira import AsyncArcmira

        client = AsyncArcmira(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.trackers.update(
                id="id",
                idempotency_key="8b2f6c3e-4d1a-4e7b-9c05-2f6a1b7d3e90",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            id,
            idempotency_key=idempotency_key,
            display_name=display_name,
            person_match_mode=person_match_mode,
            filters=filters,
            paused=paused,
            request_options=request_options,
        )
        return _response.data

    @property
    def alerts(self):
        if self._alerts is None:
            from .alerts.client import AsyncAlertsClient  # noqa: E402

            self._alerts = AsyncAlertsClient(client_wrapper=self._client_wrapper)
        return self._alerts
