# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.bad_ranking_change import BadRankingChange
from ...types.delivery_issue_change import DeliveryIssueChange
from ...types.freeform_suggested_change import FreeformSuggestedChange
from ...types.merge_suggestion_change import MergeSuggestionChange
from ...types.missed_alert_change import MissedAlertChange
from ...types.missing_result_change import MissingResultChange
from ...types.stale_metadata_change import StaleMetadataChange
from ...types.wrong_classification_change import WrongClassificationChange
from ...types.wrong_entity_change import WrongEntityChange
from ...types.wrong_entity_type_change import WrongEntityTypeChange

SubmitFeedbackRequestCorrectionsItemSuggestedChange = typing.Union[
    MergeSuggestionChange,
    WrongEntityChange,
    WrongEntityTypeChange,
    MissingResultChange,
    WrongClassificationChange,
    StaleMetadataChange,
    BadRankingChange,
    MissedAlertChange,
    DeliveryIssueChange,
    FreeformSuggestedChange,
]
