# This file was auto-generated by Fern from our API Definition.

import typing

SubmitFeedbackRequestCorrectionsItemClass = typing.Union[typing.Literal["sponsored", "organic", "mention"], typing.Any]
