# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.pagination import AsyncPager, SyncPager
from ...core.request_options import RequestOptions
from ...types.person_appearance_list_response import PersonAppearanceListResponse
from ...types.person_appearance_list_response_items_item import PersonAppearanceListResponseItemsItem
from .raw_client import AsyncRawAppearancesClient, RawAppearancesClient
from .types.list_appearances_request_is_appearance import ListAppearancesRequestIsAppearance
from .types.list_appearances_request_mode import ListAppearancesRequestMode
from .types.list_appearances_request_order import ListAppearancesRequestOrder


class AppearancesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAppearancesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAppearancesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAppearancesClient
        """
        return self._raw_client

    def list(
        self,
        slug: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        field: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        order: typing.Optional[ListAppearancesRequestOrder] = None,
        mode: typing.Optional[ListAppearancesRequestMode] = None,
        is_appearance: typing.Optional[ListAppearancesRequestIsAppearance] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SyncPager[PersonAppearanceListResponseItemsItem, PersonAppearanceListResponse]:
        """
        Appearances (the person was actually present in the media) for one person, newest first. Person-only: the equivalent route for any other entity type returns a 400 (appearances_person_only). Signed cursor pagination: rows are in items, and next_cursor (null on the last page) feeds cursor. A token binds route, filters, limit, caller and visibility; malformed or old tokens return invalid_cursor. Aggregate and display lists are live: changed ranks or deleted rows may shift later pages. total, offset, limit and hasMore mirror the web shape. The rows are display-oriented. For programmatic pagination, date filtering, and the standard mention-row shape, use GET /v1/mentions?entity_id=...&is_appearance=true instead.

        Parameters
        ----------
        slug : str
            The entity slug: the last segment of its arcmira.com page URL, as EntityRef.slug carries it.

        limit : typing.Optional[int]

        cursor : typing.Optional[str]
            Signed continuation from next_cursor. Bound to route, filters, limit, caller and visibility; invalid or old tokens return invalid_cursor. Person appearance publication pages use a media-id insertion fence; aggregate sorts remain live.

        q : typing.Optional[str]
            Substring filter over the row's text columns (e.g. video title, channel name, description).

        field : typing.Optional[str]
            Restrict the q filter to one column. Default "any" (all searchable columns).

        sort : typing.Optional[str]
            Sort key. Rows default to newest first; supported values vary by list (e.g. "date", "channel").

        order : typing.Optional[ListAppearancesRequestOrder]
            Sort direction. Default desc.

        mode : typing.Optional[ListAppearancesRequestMode]
            Person relationship lens: guest appearances or inbound mentions.

        is_appearance : typing.Optional[ListAppearancesRequestIsAppearance]
            For person appearances, true lists guest episodes and false lists inbound mentions.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SyncPager[PersonAppearanceListResponseItemsItem, PersonAppearanceListResponse]
            Success

        Examples
        --------
        from arcmira import Arcmira

        client = Arcmira(
            api_key="YOUR_API_KEY",
        )
        response = client.people.appearances.list(
            slug="slug",
        )
        for item in response:
            yield item
        # alternatively, you can paginate page-by-page
        for page in response.iter_pages():
            yield page
        """
        return self._raw_client.list(
            slug,
            limit=limit,
            cursor=cursor,
            q=q,
            field=field,
            sort=sort,
            order=order,
            mode=mode,
            is_appearance=is_appearance,
            request_options=request_options,
        )


class AsyncAppearancesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAppearancesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAppearancesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAppearancesClient
        """
        return self._raw_client

    async def list(
        self,
        slug: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        q: typing.Optional[str] = None,
        field: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        order: typing.Optional[ListAppearancesRequestOrder] = None,
        mode: typing.Optional[ListAppearancesRequestMode] = None,
        is_appearance: typing.Optional[ListAppearancesRequestIsAppearance] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncPager[PersonAppearanceListResponseItemsItem, PersonAppearanceListResponse]:
        """
        Appearances (the person was actually present in the media) for one person, newest first. Person-only: the equivalent route for any other entity type returns a 400 (appearances_person_only). Signed cursor pagination: rows are in items, and next_cursor (null on the last page) feeds cursor. A token binds route, filters, limit, caller and visibility; malformed or old tokens return invalid_cursor. Aggregate and display lists are live: changed ranks or deleted rows may shift later pages. total, offset, limit and hasMore mirror the web shape. The rows are display-oriented. For programmatic pagination, date filtering, and the standard mention-row shape, use GET /v1/mentions?entity_id=...&is_appearance=true instead.

        Parameters
        ----------
        slug : str
            The entity slug: the last segment of its arcmira.com page URL, as EntityRef.slug carries it.

        limit : typing.Optional[int]

        cursor : typing.Optional[str]
            Signed continuation from next_cursor. Bound to route, filters, limit, caller and visibility; invalid or old tokens return invalid_cursor. Person appearance publication pages use a media-id insertion fence; aggregate sorts remain live.

        q : typing.Optional[str]
            Substring filter over the row's text columns (e.g. video title, channel name, description).

        field : typing.Optional[str]
            Restrict the q filter to one column. Default "any" (all searchable columns).

        sort : typing.Optional[str]
            Sort key. Rows default to newest first; supported values vary by list (e.g. "date", "channel").

        order : typing.Optional[ListAppearancesRequestOrder]
            Sort direction. Default desc.

        mode : typing.Optional[ListAppearancesRequestMode]
            Person relationship lens: guest appearances or inbound mentions.

        is_appearance : typing.Optional[ListAppearancesRequestIsAppearance]
            For person appearances, true lists guest episodes and false lists inbound mentions.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncPager[PersonAppearanceListResponseItemsItem, PersonAppearanceListResponse]
            Success

        Examples
        --------
        import asyncio

        from arcmira import AsyncArcmira

        client = AsyncArcmira(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.people.appearances.list(
                slug="slug",
            )
            async for item in response:
                yield item

            # alternatively, you can paginate page-by-page
            async for page in response.iter_pages():
                yield page


        asyncio.run(main())
        """
        return await self._raw_client.list(
            slug,
            limit=limit,
            cursor=cursor,
            q=q,
            field=field,
            sort=sort,
            order=order,
            mode=mode,
            is_appearance=is_appearance,
            request_options=request_options,
        )
