# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.entity_cards_response import EntityCardsResponse
from ..types.entity_detail_response import EntityDetailResponse
from ..types.entity_lookup_response import EntityLookupResponse
from ..types.entity_momentum_response import EntityMomentumResponse
from ..types.entity_resolve_response import EntityResolveResponse
from ..types.entity_search_response import EntitySearchResponse
from .raw_client import AsyncRawEntitiesClient, RawEntitiesClient
from .types.lookup_entities_request_type import LookupEntitiesRequestType
from .types.resolve_entities_request_type import ResolveEntitiesRequestType
from .types.search_entities_request_type import SearchEntitiesRequestType

if typing.TYPE_CHECKING:
    from .mentions.client import AsyncMentionsClient, MentionsClient
    from .recommendations.client import AsyncRecommendationsClient, RecommendationsClient


class EntitiesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEntitiesClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._mentions: typing.Optional[MentionsClient] = None
        self._recommendations: typing.Optional[RecommendationsClient] = None

    @property
    def with_raw_response(self) -> RawEntitiesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEntitiesClient
        """
        return self._raw_client

    def search(
        self,
        *,
        q: str,
        type: typing.Optional[SearchEntitiesRequestType] = None,
        has_recommendations_data: typing.Optional[bool] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EntitySearchResponse:
        """
        Substring name search returning up to 25 entities ordered by appearance count, each with a suggested flag: true on an exact match with far more traction than any other row of its type. A q that is a YouTube channel id (UC...), an @handle, or a YouTube URL carrying either resolves to that one channel row, suggested, with its youtube_channel_id. Callers with Recommendations API access (a Pro+ plan) also receive a recommendations_summary per result when a brand profile exists.

        Parameters
        ----------
        q : str

        type : typing.Optional[SearchEntitiesRequestType]

        has_recommendations_data : typing.Optional[bool]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntitySearchResponse
            Success

        Examples
        --------
        from arcmira import Arcmira

        client = Arcmira(
            api_key="YOUR_API_KEY",
        )
        client.entities.search(
            q="q",
        )
        """
        _response = self._raw_client.search(
            q=q,
            type=type,
            has_recommendations_data=has_recommendations_data,
            limit=limit,
            request_options=request_options,
        )
        return _response.data

    def resolve(
        self,
        *,
        q: str,
        type: typing.Optional[ResolveEntitiesRequestType] = None,
        limit: typing.Optional[int] = None,
        context: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EntityResolveResponse:
        """
        Call this before passing an id to about, by, entity_ids, channel_ids or channel; those filters refuse names with id_required. Pass context with the user's own words about the name ("the startup bank", "on My First Million"). The answer is one of three: best (the name means one row: use it and name it), suggested (no row is certain but one stands out, with reason and evidence: use it and tell the user you assumed it), or ask (several rows fit: show ask.options, or check every option id and answer per row). For a show pass type=channel and use the youtube_channel_id; for a brand or a person use the id. Free; bills no rows.

        Parameters
        ----------
        q : str
            A name, @handle, YouTube URL or channel id (UC...). One thing per call.

        type : typing.Optional[ResolveEntitiesRequestType]
            Restrict candidates to one type. Pass channel for a show and read best.youtube_channel_id.

        limit : typing.Optional[int]
            Candidates to return, 1 to 15. Default 8.

        context : typing.Optional[str]
            What the user said about the name, in their words ("the startup bank", "Canada's prime minister", "on My First Million"). Ranks candidates by their description and by the episodes they share with what the context names; a clear winner comes back as suggested with reason context.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityResolveResponse
            Success

        Examples
        --------
        from arcmira import Arcmira

        client = Arcmira(
            api_key="YOUR_API_KEY",
        )
        client.entities.resolve(
            q="q",
        )
        """
        _response = self._raw_client.resolve(
            q=q, type=type, limit=limit, context=context, request_options=request_options
        )
        return _response.data

    def lookup(
        self,
        *,
        id: typing.Optional[str] = None,
        name: typing.Optional[str] = None,
        type: typing.Optional[LookupEntitiesRequestType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EntityLookupResponse:
        """
        Resolves an id or name to the canonical entity record, following merge redirects. Pass either id (ent_{n} or numeric) or name, optionally constrained by type.

        Parameters
        ----------
        id : typing.Optional[str]

        name : typing.Optional[str]

        type : typing.Optional[LookupEntitiesRequestType]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityLookupResponse
            Success

        Examples
        --------
        from arcmira import Arcmira

        client = Arcmira(
            api_key="YOUR_API_KEY",
        )
        client.entities.lookup()
        """
        _response = self._raw_client.lookup(id=id, name=name, type=type, request_options=request_options)
        return _response.data

    def cards(self, *, ids: str, request_options: typing.Optional[RequestOptions] = None) -> EntityCardsResponse:
        """
        Free endpoint (0 rows). Batched compact lookups for UI hover cards: name, slug, type, image, and index counts for up to 50 raw integer entity ids per request. Merged ids resolve to their canonical entity but are returned under the requested id; unknown ids are silently dropped. The response is identical for all viewers and CDN-cacheable.

        Parameters
        ----------
        ids : str
            Comma-separated raw integer entity ids, 1 to 50 of them (e.g. "12,844,1032"). Merged ids resolve to their canonical entity; unknown ids are silently dropped from the response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityCardsResponse
            Success

        Examples
        --------
        from arcmira import Arcmira

        client = Arcmira(
            api_key="YOUR_API_KEY",
        )
        client.entities.cards(
            ids="ids",
        )
        """
        _response = self._raw_client.cards(ids=ids, request_options=request_options)
        return _response.data

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> EntityDetailResponse:
        """
        Returns the canonical entity envelope for an ent_{n} or numeric id, following merge redirects. For organization and product entities, callers with Recommendations API access (a Pro+ plan) also receive a recommendations_summary commercial-intelligence rollup when a brand profile exists.

        Parameters
        ----------
        id : str
            Entity id, ent_{n} or the numeric id. Merged ids follow their redirect.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityDetailResponse
            Success

        Examples
        --------
        from arcmira import Arcmira

        client = Arcmira(
            api_key="YOUR_API_KEY",
        )
        client.entities.get(
            id="id",
        )
        """
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data

    def momentum(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> EntityMomentumResponse:
        """
        Mentions in the last 7 and 30 days against the prior 30, an absolute-delta verdict (accelerating, flat, fading, none), the newest media date, and the top shows in the window. It counts the shows we index, not the whole internet, and it is a count, not a score. On a Pro+ plan the card also carries paid_vs_organic; otherwise that field is absent and access names the gate. Bills one row. Every gate is a typed error whose error.unlock.url names the plan that lifts it; pass src=mcp-tool only from the Arcmira MCP server.

        Parameters
        ----------
        id : str
            Entity id, ent_{n} or the numeric id. Merged ids follow their redirect.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityMomentumResponse
            Success

        Examples
        --------
        from arcmira import Arcmira

        client = Arcmira(
            api_key="YOUR_API_KEY",
        )
        client.entities.momentum(
            id="id",
        )
        """
        _response = self._raw_client.momentum(id, request_options=request_options)
        return _response.data

    @property
    def mentions(self):
        if self._mentions is None:
            from .mentions.client import MentionsClient  # noqa: E402

            self._mentions = MentionsClient(client_wrapper=self._client_wrapper)
        return self._mentions

    @property
    def recommendations(self):
        if self._recommendations is None:
            from .recommendations.client import RecommendationsClient  # noqa: E402

            self._recommendations = RecommendationsClient(client_wrapper=self._client_wrapper)
        return self._recommendations


class AsyncEntitiesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEntitiesClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._mentions: typing.Optional[AsyncMentionsClient] = None
        self._recommendations: typing.Optional[AsyncRecommendationsClient] = None

    @property
    def with_raw_response(self) -> AsyncRawEntitiesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEntitiesClient
        """
        return self._raw_client

    async def search(
        self,
        *,
        q: str,
        type: typing.Optional[SearchEntitiesRequestType] = None,
        has_recommendations_data: typing.Optional[bool] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EntitySearchResponse:
        """
        Substring name search returning up to 25 entities ordered by appearance count, each with a suggested flag: true on an exact match with far more traction than any other row of its type. A q that is a YouTube channel id (UC...), an @handle, or a YouTube URL carrying either resolves to that one channel row, suggested, with its youtube_channel_id. Callers with Recommendations API access (a Pro+ plan) also receive a recommendations_summary per result when a brand profile exists.

        Parameters
        ----------
        q : str

        type : typing.Optional[SearchEntitiesRequestType]

        has_recommendations_data : typing.Optional[bool]

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntitySearchResponse
            Success

        Examples
        --------
        import asyncio

        from arcmira import AsyncArcmira

        client = AsyncArcmira(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.entities.search(
                q="q",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search(
            q=q,
            type=type,
            has_recommendations_data=has_recommendations_data,
            limit=limit,
            request_options=request_options,
        )
        return _response.data

    async def resolve(
        self,
        *,
        q: str,
        type: typing.Optional[ResolveEntitiesRequestType] = None,
        limit: typing.Optional[int] = None,
        context: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EntityResolveResponse:
        """
        Call this before passing an id to about, by, entity_ids, channel_ids or channel; those filters refuse names with id_required. Pass context with the user's own words about the name ("the startup bank", "on My First Million"). The answer is one of three: best (the name means one row: use it and name it), suggested (no row is certain but one stands out, with reason and evidence: use it and tell the user you assumed it), or ask (several rows fit: show ask.options, or check every option id and answer per row). For a show pass type=channel and use the youtube_channel_id; for a brand or a person use the id. Free; bills no rows.

        Parameters
        ----------
        q : str
            A name, @handle, YouTube URL or channel id (UC...). One thing per call.

        type : typing.Optional[ResolveEntitiesRequestType]
            Restrict candidates to one type. Pass channel for a show and read best.youtube_channel_id.

        limit : typing.Optional[int]
            Candidates to return, 1 to 15. Default 8.

        context : typing.Optional[str]
            What the user said about the name, in their words ("the startup bank", "Canada's prime minister", "on My First Million"). Ranks candidates by their description and by the episodes they share with what the context names; a clear winner comes back as suggested with reason context.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityResolveResponse
            Success

        Examples
        --------
        import asyncio

        from arcmira import AsyncArcmira

        client = AsyncArcmira(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.entities.resolve(
                q="q",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.resolve(
            q=q, type=type, limit=limit, context=context, request_options=request_options
        )
        return _response.data

    async def lookup(
        self,
        *,
        id: typing.Optional[str] = None,
        name: typing.Optional[str] = None,
        type: typing.Optional[LookupEntitiesRequestType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EntityLookupResponse:
        """
        Resolves an id or name to the canonical entity record, following merge redirects. Pass either id (ent_{n} or numeric) or name, optionally constrained by type.

        Parameters
        ----------
        id : typing.Optional[str]

        name : typing.Optional[str]

        type : typing.Optional[LookupEntitiesRequestType]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityLookupResponse
            Success

        Examples
        --------
        import asyncio

        from arcmira import AsyncArcmira

        client = AsyncArcmira(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.entities.lookup()


        asyncio.run(main())
        """
        _response = await self._raw_client.lookup(id=id, name=name, type=type, request_options=request_options)
        return _response.data

    async def cards(self, *, ids: str, request_options: typing.Optional[RequestOptions] = None) -> EntityCardsResponse:
        """
        Free endpoint (0 rows). Batched compact lookups for UI hover cards: name, slug, type, image, and index counts for up to 50 raw integer entity ids per request. Merged ids resolve to their canonical entity but are returned under the requested id; unknown ids are silently dropped. The response is identical for all viewers and CDN-cacheable.

        Parameters
        ----------
        ids : str
            Comma-separated raw integer entity ids, 1 to 50 of them (e.g. "12,844,1032"). Merged ids resolve to their canonical entity; unknown ids are silently dropped from the response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityCardsResponse
            Success

        Examples
        --------
        import asyncio

        from arcmira import AsyncArcmira

        client = AsyncArcmira(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.entities.cards(
                ids="ids",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cards(ids=ids, request_options=request_options)
        return _response.data

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> EntityDetailResponse:
        """
        Returns the canonical entity envelope for an ent_{n} or numeric id, following merge redirects. For organization and product entities, callers with Recommendations API access (a Pro+ plan) also receive a recommendations_summary commercial-intelligence rollup when a brand profile exists.

        Parameters
        ----------
        id : str
            Entity id, ent_{n} or the numeric id. Merged ids follow their redirect.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityDetailResponse
            Success

        Examples
        --------
        import asyncio

        from arcmira import AsyncArcmira

        client = AsyncArcmira(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.entities.get(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data

    async def momentum(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EntityMomentumResponse:
        """
        Mentions in the last 7 and 30 days against the prior 30, an absolute-delta verdict (accelerating, flat, fading, none), the newest media date, and the top shows in the window. It counts the shows we index, not the whole internet, and it is a count, not a score. On a Pro+ plan the card also carries paid_vs_organic; otherwise that field is absent and access names the gate. Bills one row. Every gate is a typed error whose error.unlock.url names the plan that lifts it; pass src=mcp-tool only from the Arcmira MCP server.

        Parameters
        ----------
        id : str
            Entity id, ent_{n} or the numeric id. Merged ids follow their redirect.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityMomentumResponse
            Success

        Examples
        --------
        import asyncio

        from arcmira import AsyncArcmira

        client = AsyncArcmira(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.entities.momentum(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.momentum(id, request_options=request_options)
        return _response.data

    @property
    def mentions(self):
        if self._mentions is None:
            from .mentions.client import AsyncMentionsClient  # noqa: E402

            self._mentions = AsyncMentionsClient(client_wrapper=self._client_wrapper)
        return self._mentions

    @property
    def recommendations(self):
        if self._recommendations is None:
            from .recommendations.client import AsyncRecommendationsClient  # noqa: E402

            self._recommendations = AsyncRecommendationsClient(client_wrapper=self._client_wrapper)
        return self._recommendations
