# This file was auto-generated by Fern from our API Definition.

import typing

ListRecommendationsRequestMentionClass = typing.Union[
    typing.Literal["ad_read", "endorsement", "mention", "all"], typing.Any
]
